<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Supported Locales
    |--------------------------------------------------------------------------
    |
    | List of locales that your application will support.
    | Uncomment or add new locales as needed.
    |
    */

    'supported_locales' => [
        // 'aa' => ['name' => 'Afar', 'native' => 'Afar', 'script' => 'Latn'],
        // 'aa_DJ' => ['name' => 'Afar (Djibouti)', 'native' => 'Afar (Djibouti)', 'script' => 'Latn'],
        // 'aa_ER' => ['name' => 'Afar (Eritrea)', 'native' => 'Afar (Eritrea)', 'script' => 'Latn'],
        // 'aa_ET' => ['name' => 'Afar (Ethiopia)', 'native' => 'Afar (Ethiopia)', 'script' => 'Latn'],
        // 'af' => ['name' => 'Afrikaans', 'native' => 'Afrikaans', 'script' => 'Latn'],
        // 'af_NA' => ['name' => 'Afrikaans (Namibia)', 'native' => 'Afrikaans (Namibië)', 'script' => 'Latn'],
        // 'af_ZA' => ['name' => 'Afrikaans (South Africa)', 'native' => 'Afrikaans (Suid-Afrika)', 'script' => 'Latn'],
        // 'agq' => ['name' => 'Aghem', 'native' => 'Aghem', 'script' => 'Latn'],
        // 'agq_CM' => ['name' => 'Aghem (Cameroon)', 'native' => 'Aghem (Cameroon)', 'script' => 'Latn'],
        // 'ak' => ['name' => 'Akan', 'native' => 'Akan', 'script' => 'Latn'],
        // 'ak_GH' => ['name' => 'Akan (Ghana)', 'native' => 'Akan (Ghana)', 'script' => 'Latn'],
        // 'sq' => ['name' => 'Albanian', 'native' => 'Shqip', 'script' => 'Latn'],
        // 'sq_AL' => ['name' => 'Albanian (Albania)', 'native' => 'Shqip (Shqipëri)', 'script' => 'Latn'],
        // 'sq_MK' => ['name' => 'Albanian (North Macedonia)', 'native' => 'Shqip (Maqedonia e Veriut)', 'script' => 'Latn'],
        // 'gsw' => ['name' => 'Alsatian', 'native' => 'Elsässisch', 'script' => 'Latn'],
        // 'gsw_FR' => ['name' => 'Alsatian (France)', 'native' => 'Elsässisch (Frankreich)', 'script' => 'Latn'],
        // 'gsw_LI' => ['name' => 'Alsatian (Liechtenstein)', 'native' => 'Elsässisch (Liechtenstein)', 'script' => 'Latn'],
        // 'gsw_CH' => ['name' => 'Alsatian (Switzerland)', 'native' => 'Elsässisch (Schweiz)', 'script' => 'Latn'],
        // 'am' => ['name' => 'Amharic', 'native' => 'አማርኛ', 'script' => 'Ethi'],
        // 'am_ET' => ['name' => 'Amharic (Ethiopia)', 'native' => 'አማርኛ (ኢትዮጵያ)', 'script' => 'Ethi'],
        'ar' => ['name' => 'Arabic', 'native' => 'العربية', 'script' => 'Arab'],
        // 'ar_DZ' => ['name' => 'Arabic (Algeria)', 'native' => 'العربية (الجزائر)', 'script' => 'Arab'],
        // 'ar_BH' => ['name' => 'Arabic (Bahrain)', 'native' => 'العربية (البحرين)', 'script' => 'Arab'],
        // 'ar_TD' => ['name' => 'Arabic (Chad)', 'native' => 'العربية (تشاد)', 'script' => 'Arab'],
        // 'ar_KM' => ['name' => 'Arabic (Comoros)', 'native' => 'العربية (جزر القمر)', 'script' => 'Arab'],
        // 'ar_DJ' => ['name' => 'Arabic (Djibouti)', 'native' => 'العربية (جيبوتي)', 'script' => 'Arab'],
        // 'ar_EG' => ['name' => 'Arabic (Egypt)', 'native' => 'العربية (مصر)', 'script' => 'Arab'],
        // 'ar_ER' => ['name' => 'Arabic (Eritrea)', 'native' => 'العربية (إريتريا)', 'script' => 'Arab'],
        // 'ar_IQ' => ['name' => 'Arabic (Iraq)', 'native' => 'العربية (العراق)', 'script' => 'Arab'],
        // 'ar_JO' => ['name' => 'Arabic (Jordan)', 'native' => 'العربية (الأردن)', 'script' => 'Arab'],
        // 'ar_KW' => ['name' => 'Arabic (Kuwait)', 'native' => 'العربية (الكويت)', 'script' => 'Arab'],
        // 'ar_LB' => ['name' => 'Arabic (Lebanon)', 'native' => 'العربية (لبنان)', 'script' => 'Arab'],
        // 'ar_LY' => ['name' => 'Arabic (Libya)', 'native' => 'العربية (ليبيا)', 'script' => 'Arab'],
        // 'ar_MR' => ['name' => 'Arabic (Mauritania)', 'native' => 'العربية (موريتانيا)', 'script' => 'Arab'],
        // 'ar_MA' => ['name' => 'Arabic (Morocco)', 'native' => 'العربية (المغرب)', 'script' => 'Arab'],
        // 'ar_OM' => ['name' => 'Arabic (Oman)', 'native' => 'العربية (عمان)', 'script' => 'Arab'],
        // 'ar_PS' => ['name' => 'Arabic (Palestine)', 'native' => 'العربية (فلسطين)', 'script' => 'Arab'],
        // 'ar_QA' => ['name' => 'Arabic (Qatar)', 'native' => 'العربية (قطر)', 'script' => 'Arab'],
        // 'ar_SA' => ['name' => 'Arabic (Saudi Arabia)', 'native' => 'العربية (المملكة العربية السعودية)', 'script' => 'Arab'],
        // 'ar_SO' => ['name' => 'Arabic (Somalia)', 'native' => 'العربية (الصومال)', 'script' => 'Arab'],
        // 'ar_SS' => ['name' => 'Arabic (South Sudan)', 'native' => 'العربية (جنوب السودان)', 'script' => 'Arab'],
        // 'ar_SD' => ['name' => 'Arabic (Sudan)', 'native' => 'العربية (السودان)', 'script' => 'Arab'],
        // 'ar_SY' => ['name' => 'Arabic (Syria)', 'native' => 'العربية (سوريا)', 'script' => 'Arab'],
        // 'ar_TN' => ['name' => 'Arabic (Tunisia)', 'native' => 'العربية (تونس)', 'script' => 'Arab'],
        // 'ar_AE' => ['name' => 'Arabic (United Arab Emirates)', 'native' => 'العربية (الإمارات العربية المتحدة)', 'script' => 'Arab'],
        // 'ar_001' => ['name' => 'Arabic (World)', 'native' => 'العربية (العالم)', 'script' => 'Arab'],
        // 'ar_YE' => ['name' => 'Arabic (Yemen)', 'native' => 'العربية (اليمن)', 'script' => 'Arab'],
        // 'hy' => ['name' => 'Armenian', 'native' => 'Հայերեն', 'script' => 'Armn'],
        // 'hy_AM' => ['name' => 'Armenian (Armenia)', 'native' => 'Հայերեն (Հայաստան)', 'script' => 'Armn'],
        // 'as' => ['name' => 'Assamese', 'native' => 'অসমীয়া', 'script' => 'Beng'],
        // 'as_IN' => ['name' => 'Assamese (India)', 'native' => 'অসমীয়া (ভাৰত)', 'script' => 'Beng'],
        // 'ast' => ['name' => 'Asturian', 'native' => 'Asturianu', 'script' => 'Latn'],
        // 'ast_ES' => ['name' => 'Asturian (Spain)', 'native' => 'Asturianu (España)', 'script' => 'Latn'],
        // 'asa' => ['name' => 'Asu', 'native' => 'Kuasai', 'script' => 'Latn'],
        // 'asa_TZ' => ['name' => 'Asu (Tanzania)', 'native' => 'Kuasai (Tanzania)', 'script' => 'Latn'],
        // 'az_Cyrl' => ['name' => 'Azerbaijani (Cyrillic)', 'native' => 'Азәрбајҹан (Кирил)', 'script' => 'Cyrl'],
        // 'az_Cyrl_AZ' => ['name' => 'Azerbaijani (Cyrillic, Azerbaijan)', 'native' => 'Азәрбајҹан (Кирил, Азәрбајҹан)', 'script' => 'Cyrl'],
        // 'az' => ['name' => 'Azerbaijani', 'native' => 'Azərbaycanca', 'script' => 'Latn'],
        // 'az_Latn' => ['name' => 'Azerbaijani (Latin)', 'native' => 'Azərbaycanca (Latın)', 'script' => 'Latn'],
        // 'az_Latn_AZ' => ['name' => 'Azerbaijani (Latin, Azerbaijan)', 'native' => 'Azərbaycanca (Latın, Azərbaycan)', 'script' => 'Latn'],
        // 'ksf' => ['name' => 'Bafia', 'native' => 'Bafia', 'script' => 'Latn'],
        // 'ksf_CM' => ['name' => 'Bafia (Cameroon)', 'native' => 'Bafia (Cameroun)', 'script' => 'Latn'],
        // 'bm' => ['name' => 'Bambara', 'native' => 'Bamanankan', 'script' => 'Latn'],
        // 'bm_Latn_ML' => ['name' => 'Bambara (Latin, Mali)', 'native' => 'Bamanankan (Latn, Mali)', 'script' => 'Latn'],
        // 'bn' => ['name' => 'Bengali', 'native' => 'বাংলা', 'script' => 'Beng'],
        // 'bn_BD' => ['name' => 'Bengali (Bangladesh)', 'native' => 'বাংলা (বাংলাদেশ)', 'script' => 'Beng'],
        // 'bn_IN' => ['name' => 'Bengali (India)', 'native' => 'বাংলা (ভাৰত)', 'script' => 'Beng'],
        // 'bas' => ['name' => 'Basa', 'native' => 'Ɓàsàa', 'script' => 'Latn'],
        // 'bas_CM' => ['name' => 'Basa (Cameroon)', 'native' => 'Ɓàsàa (Kàmerûn)', 'script' => 'Latn'],
        // 'ba' => ['name' => 'Bashkir', 'native' => 'Башҡорт', 'script' => 'Cyrl'],
        // 'ba_RU' => ['name' => 'Bashkir (Russia)', 'native' => 'Башҡорт (Россия)', 'script' => 'Cyrl'],
        // 'eu' => ['name' => 'Basque', 'native' => 'Euskara', 'script' => 'Latn'],
        // 'eu_ES' => ['name' => 'Basque (Spain)', 'native' => 'Euskara (Espainia)', 'script' => 'Latn'],
        // 'be' => ['name' => 'Belarusian', 'native' => 'Беларуская', 'script' => 'Cyrl'],
        // 'be_BY' => ['name' => 'Belarusian (Belarus)', 'native' => 'Беларуская (Беларусь)', 'script' => 'Cyrl'],
        // 'bem' => ['name' => 'Bemba', 'native' => 'Ichibemba', 'script' => 'Latn'],
        // 'bem_ZM' => ['name' => 'Bemba (Zambia)', 'native' => 'Ichibemba (Zambia)', 'script' => 'Latn'],
        // 'bez' => ['name' => 'Bena', 'native' => 'Hibena', 'script' => 'Latn'],
        // 'bez_TZ' => ['name' => 'Bena (Tanzania)', 'native' => 'Hibena (Hutanzania)', 'script' => 'Latn'],
        // 'byn' => ['name' => 'Blin', 'native' => 'ብሊን', 'script' => 'Ethi'],
        // 'byn_ER' => ['name' => 'Blin (Eritrea)', 'native' => 'ብሊን (ኤርትራ)', 'script' => 'Ethi'],
        // 'brx' => ['name' => 'Bodo', 'native' => 'बड़ो', 'script' => 'Deva'],
        // 'brx_IN' => ['name' => 'Bodo (India)', 'native' => 'बड़ो (भारत)', 'script' => 'Deva'],
        // 'bs_Cyrl' => ['name' => 'Bosnian (Cyrillic)', 'native' => 'Босански (Ћирилица)', 'script' => 'Cyrl'],
        // 'bs_Cyrl_BA' => ['name' => 'Bosnian (Cyrillic, Bosnia and Herzegovina)', 'native' => 'Босански (Ћирилица, Босна и Херцеговина)', 'script' => 'Cyrl'],
        // 'bs_Latn' => ['name' => 'Bosnian (Latin)', 'native' => 'Bosanski (Latinica)', 'script' => 'Latn'],
        // 'bs' => ['name' => 'Bosnian', 'native' => 'Bosanski', 'script' => 'Latn'],
        // 'bs_Latn_BA' => ['name' => 'Bosnian (Latin, Bosnia and Herzegovina)', 'native' => 'Bosanski (Latinica, Bosna i Hercegovina)', 'script' => 'Latn'],
        // 'br' => ['name' => 'Breton', 'native' => 'Brezhoneg', 'script' => 'Latn'],
        // 'br_FR' => ['name' => 'Breton (France)', 'native' => 'Brezhoneg (Frañs)', 'script' => 'Latn'],
        // 'bg' => ['name' => 'Bulgarian', 'native' => 'Български', 'script' => 'Cyrl'],
        // 'bg_BG' => ['name' => 'Bulgarian (Bulgaria)', 'native' => 'Български (България)', 'script' => 'Cyrl'],
        // 'my' => ['name' => 'Burmese', 'native' => 'မြန်မာ', 'script' => 'Mymr'],
        // 'my_MM' => ['name' => 'Burmese (Myanmar [Burma])', 'native' => 'မြန်မာ (မြန်မာ [မြန်မာ])', 'script' => 'Mymr'],
        // 'ca' => ['name' => 'Catalan', 'native' => 'Català', 'script' => 'Latn'],
        // 'ca_AD' => ['name' => 'Catalan (Andorra)', 'native' => 'Català (Andorra)', 'script' => 'Latn'],
        // 'ca_FR' => ['name' => 'Catalan (France)', 'native' => 'Català (França)', 'script' => 'Latn'],
        // 'ca_IT' => ['name' => 'Catalan (Italy)', 'native' => 'Català (Itàlia)', 'script' => 'Latn'],
        // 'ca_ES' => ['name' => 'Catalan (Spain)', 'native' => 'Català (Espanya)', 'script' => 'Latn'],
        // 'ceb' => ['name' => 'Cebuano', 'native' => 'Cebuano', 'script' => 'Latn'],
        // 'ceb_Latn' => ['name' => 'Cebuano (Latin)', 'native' => 'Cebuano (Latino)', 'script' => 'Latn'],
        // 'ceb_Latn_PH' => ['name' => 'Cebuano (Latin, Philippines)', 'native' => 'Cebuano (Latino, Pilipinas)', 'script' => 'Latn'],
        // 'tzm_Arab_MA' => ['name' => 'Central Atlas Tamazight (Arabic, Morocco)', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ (العربية, المغرب)', 'script' => 'Arab'],
        // 'tzm_Latn_MA' => ['name' => 'Central Atlas Tamazight (Latin, Morocco)', 'native' => 'Tamaziɣt n laṭlaṣ (Laṭin, lmɣrib)', 'script' => 'Latn'],
        // 'ku' => ['name' => 'Kurdish', 'native' => 'Kurdî', 'script' => 'Latn'],
        // 'ku_Arab' => ['name' => 'Kurdish (Arabic)', 'native' => 'كوردی (عەرەبی)', 'script' => 'Arab'],
        // 'ku_Arab_IQ' => ['name' => 'Kurdish (Arabic, Iraq)', 'native' => 'كوردی (عەرەبی, عێراق)', 'script' => 'Arab'],
        // 'ccp' => ['name' => 'Chakma', 'native' => '𑄌𑄋𑄴𑄟𑄳𑄦', 'script' => 'Cakm'],
        // 'ccp_Cakm' => ['name' => 'Chakma (Chakma)', 'native' => '𑄌𑄋𑄴𑄟𑄳𑄦 (𑄌𑄋𑄴𑄟𑄳𑄦)', 'script' => 'Cakm'],
        // 'ccp_Cakm_BD' => ['name' => 'Chakma (Chakma, Bangladesh)', 'native' => '𑄌𑄋𑄴𑄟𑄳𑄦 (𑄌𑄋𑄴𑄟𑄳𑄦, বাংলাদেশ)', 'script' => 'Cakm'],
        // 'ccp_Cakm_IN' => ['name' => 'Chakma (Chakma, India)', 'native' => '𑄌𑄋𑄴𑄟𑄳𑄦 (𑄌𑄋𑄴𑄟𑄳𑄦, भारत)', 'script' => 'Cakm'],
        // 'ce_RU' => ['name' => 'Chechen (Russia)', 'native' => 'Нохчийн (Росси)', 'script' => 'Cyrl'],
        // 'chr' => ['name' => 'Cherokee', 'native' => 'ᏣᎳᎩ', 'script' => 'Cher'],
        // 'chr_Cher' => ['name' => 'Cherokee (Cherokee)', 'native' => 'ᏣᎳᎩ (ᏣᎳᎩ)', 'script' => 'Cher'],
        // 'chr_Cher_US' => ['name' => 'Cherokee (Cherokee, United States)', 'native' => 'ᏣᎳᎩ (ᏣᎳᎩ, ᎠᏰᎵᎯᏍᎪᎯ)', 'script' => 'Cher'],
        // 'cgg' => ['name' => 'Chiga', 'native' => 'Rukiga', 'script' => 'Latn'],
        // 'cgg_UG' => ['name' => 'Chiga (Uganda)', 'native' => 'Rukiga (Uganda)', 'script' => 'Latn'],
        // 'zh_Hans' => ['name' => 'Chinese (Simplified Han)', 'native' => '中文（简体字）', 'script' => 'Hans'],
        // 'zh' => ['name' => 'Chinese', 'native' => '中文', 'script' => 'Hans'],
        // 'zh_CN' => ['name' => 'Chinese (Simplified Han, China)', 'native' => '中文（简体字，中国）', 'script' => 'Hans'],
        // 'zh_SG' => ['name' => 'Chinese (Simplified Han, Singapore)', 'native' => '中文（简体字，新加坡）', 'script' => 'Hans'],
        // 'zh_Hant' => ['name' => 'Chinese (Traditional Han)', 'native' => '中文（繁體字）', 'script' => 'Hant'],
        // 'zh_HK' => ['name' => 'Chinese (Traditional Han, Hong Kong SAR China)', 'native' => '中文（繁體字，中华人民共和国香港特别行政区）', 'script' => 'Hant'],
        // 'zh_MO' => ['name' => 'Chinese (Traditional Han, Macau SAR China)', 'native' => '中文（繁體字，中华人民共和国澳门特别行政区）', 'script' => 'Hant'],
        // 'zh_TW' => ['name' => 'Chinese (Traditional Han, Taiwan)', 'native' => '中文（繁體字，中华民国台湾省）', 'script' => 'Hant'],
        // 'cu_RU' => ['name' => 'Church Slavic (Russia)', 'native' => 'Словѣ́ньскъ', 'script' => 'Cyrl'],
        // 'swc' => ['name' => 'Congo Swahili', 'native' => 'Kiswahili', 'script' => 'Latn'],
        // 'swc_CD' => ['name' => 'Congo Swahili (Congo [DRC])', 'native' => 'Kiswahili (Congo [Jamhuri ya Kidemokrasia ya Kongo])', 'script' => 'Latn'],
        // 'kw' => ['name' => 'Cornish', 'native' => 'Kernewek', 'script' => 'Latn'],
        // 'kw_GB' => ['name' => 'Cornish (United Kingdom)', 'native' => 'Kernewek (Rywvaneth Unys)', 'script' => 'Latn'],
        // 'co' => ['name' => 'Corsican', 'native' => 'Corsu', 'script' => 'Latn'],
        // 'co_FR' => ['name' => 'Corsican (France)', 'native' => 'Corsu (France)', 'script' => 'Latn'],
        // 'hr' => ['name' => 'Croatian', 'native' => 'Hrvatski', 'script' => 'Latn'],
        // 'hr_HR' => ['name' => 'Croatian (Croatia)', 'native' => 'Hrvatski (Hrvatska)', 'script' => 'Latn'],
        // 'hr_BA' => ['name' => 'Croatian (Bosnia and Herzegovina)', 'native' => 'Hrvatski (Bosna i Hercegovina)', 'script' => 'Latn'],
        // 'cs' => ['name' => 'Czech', 'native' => 'Čeština', 'script' => 'Latn'],
        // 'cs_CZ' => ['name' => 'Czech (Czech Republic)', 'native' => 'Čeština (Česká republika)', 'script' => 'Latn'],
        // 'da' => ['name' => 'Danish', 'native' => 'Dansk', 'script' => 'Latn'],
        // 'da_DK' => ['name' => 'Danish (Denmark)', 'native' => 'Dansk (Danmark)', 'script' => 'Latn'],
        // 'da_GL' => ['name' => 'Danish (Greenland)', 'native' => 'Dansk (Grønland)', 'script' => 'Latn'],
        // 'prs' => ['name' => 'Dari', 'native' => 'درى', 'script' => 'Arab'],
        // 'prs_AF' => ['name' => 'Dari (Afghanistan)', 'native' => 'درى (افغانستان)', 'script' => 'Arab'],
        // 'dv' => ['name' => 'Divehi', 'native' => 'ދިވެހިބަސް', 'script' => 'Thaa'],
        // 'dv_MV' => ['name' => 'Divehi (Maldives)', 'native' => 'ދިވެހިބަސް (ދިވެހިބަސް)', 'script' => 'Thaa'],
        // 'dua' => ['name' => 'Duala', 'native' => 'Duálá', 'script' => 'Latn'],
        // 'dua_CM' => ['name' => 'Duala (Cameroon)', 'native' => 'Duálá (Kamɛrún)', 'script' => 'Latn'],
        // 'nl' => ['name' => 'Dutch', 'native' => 'Nederlands', 'script' => 'Latn'],
        // 'nl_AW' => ['name' => 'Dutch (Aruba)', 'native' => 'Nederlands (Aruba)', 'script' => 'Latn'],
        // 'nl_BE' => ['name' => 'Dutch (Belgium)', 'native' => 'Nederlands (België)', 'script' => 'Latn'],
        // 'nl_BQ' => ['name' => 'Dutch (Caribbean Netherlands)', 'native' => 'Nederlands (Caribisch Nederland)', 'script' => 'Latn'],
        // 'nl_CW' => ['name' => 'Dutch (Curaçao)', 'native' => 'Nederlands (Curaçao)', 'script' => 'Latn'],
        // 'nl_NL' => ['name' => 'Dutch (Netherlands)', 'native' => 'Nederlands (Nederland)', 'script' => 'Latn'],
        // 'nl_SX' => ['name' => 'Dutch (Sint Maarten)', 'native' => 'Nederlands (Sint-Maarten)', 'script' => 'Latn'],
        // 'nl_SR' => ['name' => 'Dutch (Suriname)', 'native' => 'Nederlands (Suriname)', 'script' => 'Latn'],
        // 'dz' => ['name' => 'Dzongkha', 'native' => 'རྫོང་ཁ', 'script' => 'Tibt'],
        // 'dz_BT' => ['name' => 'Dzongkha (Bhutan)', 'native' => 'རྫོང་ཁ (འབྲུག་ཡུལ)', 'script' => 'Tibt'],
        // 'ebu' => ['name' => 'Embu', 'native' => 'Kĩembu', 'script' => 'Latn'],
        // 'ebu_KE' => ['name' => 'Embu (Kenya)', 'native' => 'Kĩembu (Kenya)', 'script' => 'Latn'],
        'en' => ['name' => 'English', 'native' => 'English', 'script' => 'Latn'],
        // 'en_AS' => ['name' => 'English (American Samoa)', 'native' => 'English (American Samoa)', 'script' => 'Latn'],
        // 'en_AI' => ['name' => 'English (Anguilla)', 'native' => 'English (Anguilla)', 'script' => 'Latn'],
        // 'en_AG' => ['name' => 'English (Antigua and Barbuda)', 'native' => 'English (Antigua and Barbuda)', 'script' => 'Latn'],
        // 'en_AU' => ['name' => 'English (Australia)', 'native' => 'English (Australia)', 'script' => 'Latn'],
        // 'en_AT' => ['name' => 'English (Austria)', 'native' => 'English (Austria)', 'script' => 'Latn'],
        // 'en_BS' => ['name' => 'English (Bahamas)', 'native' => 'English (Bahamas)', 'script' => 'Latn'],
        // 'en_BB' => ['name' => 'English (Barbados)', 'native' => 'English (Barbados)', 'script' => 'Latn'],
        // 'en_BE' => ['name' => 'English (Belgium)', 'native' => 'English (Belgium)', 'script' => 'Latn'],
        // 'en_BZ' => ['name' => 'English (Belize)', 'native' => 'English (Belize)', 'script' => 'Latn'],
        // 'en_BM' => ['name' => 'English (Bermuda)', 'native' => 'English (Bermuda)', 'script' => 'Latn'],
        // 'en_BW' => ['name' => 'English (Botswana)', 'native' => 'English (Botswana)', 'script' => 'Latn'],
        // 'en_IO' => ['name' => 'English (British Indian Ocean Territory)', 'native' => 'English (British Indian Ocean Territory)', 'script' => 'Latn'],
        // 'en_VG' => ['name' => 'English (British Virgin Islands)', 'native' => 'English (British Virgin Islands)', 'script' => 'Latn'],
        // 'en_BI' => ['name' => 'English (Burundi)', 'native' => 'English (Burundi)', 'script' => 'Latn'],
        // 'en_CM' => ['name' => 'English (Cameroon)', 'native' => 'English (Cameroon)', 'script' => 'Latn'],
        // 'en_CA' => ['name' => 'English (Canada)', 'native' => 'English (Canada)', 'script' => 'Latn'],
        // 'en_029' => ['name' => 'English (Caribbean)', 'native' => 'English (Caribbean)', 'script' => 'Latn'],
        // 'en_KY' => ['name' => 'English (Cayman Islands)', 'native' => 'English (Cayman Islands)', 'script' => 'Latn'],
        // 'en_CX' => ['name' => 'English (Christmas Island)', 'native' => 'English (Christmas Island)', 'script' => 'Latn'],
        // 'en_CC' => ['name' => 'English (Cocos [Keeling] Islands)', 'native' => 'English (Cocos [Keeling] Islands)', 'script' => 'Latn'],
        // 'en_CK' => ['name' => 'English (Cook Islands)', 'native' => 'English (Cook Islands)', 'script' => 'Latn'],
        // 'en_CY' => ['name' => 'English (Cyprus)', 'native' => 'English (Cyprus)', 'script' => 'Latn'],
        // 'en_DK' => ['name' => 'English (Denmark)', 'native' => 'English (Denmark)', 'script' => 'Latn'],
        // 'en_DM' => ['name' => 'English (Dominica)', 'native' => 'English (Dominica)', 'script' => 'Latn'],
        // 'en_ER' => ['name' => 'English (Eritrea)', 'native' => 'English (Eritrea)', 'script' => 'Latn'],
        // 'en_150' => ['name' => 'English (Europe)', 'native' => 'English (Europe)', 'script' => 'Latn'],
        // 'en_FK' => ['name' => 'English (Falkland Islands)', 'native' => 'English (Falkland Islands)', 'script' => 'Latn'],
        // 'en_FI' => ['name' => 'English (Finland)', 'native' => 'English (Finland)', 'script' => 'Latn'],
        // 'en_FJ' => ['name' => 'English (Fiji)', 'native' => 'English (Fiji)', 'script' => 'Latn'],
        // 'en_GM' => ['name' => 'English (Gambia)', 'native' => 'English (Gambia)', 'script' => 'Latn'],
        // 'en_DE' => ['name' => 'English (Germany)', 'native' => 'English (Germany)', 'script' => 'Latn'],
        // 'en_GH' => ['name' => 'English (Ghana)', 'native' => 'English (Ghana)', 'script' => 'Latn'],
        // 'en_GI' => ['name' => 'English (Gibraltar)', 'native' => 'English (Gibraltar)', 'script' => 'Latn'],
        // 'en_GD' => ['name' => 'English (Grenada)', 'native' => 'English (Grenada)', 'script' => 'Latn'],
        // 'en_GU' => ['name' => 'English (Guam)', 'native' => 'English (Guam)', 'script' => 'Latn'],
        // 'en_GG' => ['name' => 'English (Guernsey)', 'native' => 'English (Guernsey)', 'script' => 'Latn'],
        // 'en_GY' => ['name' => 'English (Guyana)', 'native' => 'English (Guyana)', 'script' => 'Latn'],
        // 'en_HK' => ['name' => 'English (Hong Kong SAR China)', 'native' => 'English (Hong Kong SAR China)', 'script' => 'Latn'],
        // 'en_IN' => ['name' => 'English (India)', 'native' => 'English (India)', 'script' => 'Latn'],
        // 'en_IE' => ['name' => 'English (Ireland)', 'native' => 'English (Ireland)', 'script' => 'Latn'],
        // 'en_IM' => ['name' => 'English (Isle of Man)', 'native' => 'English (Isle of Man)', 'script' => 'Latn'],
        // 'en_JM' => ['name' => 'English (Jamaica)', 'native' => 'English (Jamaica)', 'script' => 'Latn'],
        // 'en_JE' => ['name' => 'English (Jersey)', 'native' => 'English (Jersey)', 'script' => 'Latn'],
        // 'en_KE' => ['name' => 'English (Kenya)', 'native' => 'English (Kenya)', 'script' => 'Latn'],
        // 'en_KI' => ['name' => 'English (Kiribati)', 'native' => 'English (Kiribati)', 'script' => 'Latn'],
        // 'en_LS' => ['name' => 'English (Lesotho)', 'native' => 'English (Lesotho)', 'script' => 'Latn'],
        // 'en_LR' => ['name' => 'English (Liberia)', 'native' => 'English (Liberia)', 'script' => 'Latn'],
        // 'en_MO' => ['name' => 'English (Macau SAR China)', 'native' => 'English (Macau SAR China)', 'script' => 'Latn'],
        // 'en_MG' => ['name' => 'English (Madagascar)', 'native' => 'English (Madagascar)', 'script' => 'Latn'],
        // 'en_MW' => ['name' => 'English (Malawi)', 'native' => 'English (Malawi)', 'script' => 'Latn'],
        // 'en_MY' => ['name' => 'English (Malaysia)', 'native' => 'English (Malaysia)', 'script' => 'Latn'],
        // 'en_MT' => ['name' => 'English (Malta)', 'native' => 'English (Malta)', 'script' => 'Latn'],
        // 'en_MH' => ['name' => 'English (Marshall Islands)', 'native' => 'English (Marshall Islands)', 'script' => 'Latn'],
        // 'en_MU' => ['name' => 'English (Mauritius)', 'native' => 'English (Mauritius)', 'script' => 'Latn'],
        // 'en_FM' => ['name' => 'English (Micronesia)', 'native' => 'English (Micronesia)', 'script' => 'Latn'],
        // 'en_MS' => ['name' => 'English (Montserrat)', 'native' => 'English (Montserrat)', 'script' => 'Latn'],
        // 'en_NA' => ['name' => 'English (Namibia)', 'native' => 'English (Namibia)', 'script' => 'Latn'],
        // 'en_NR' => ['name' => 'English (Nauru)', 'native' => 'English (Nauru)', 'script' => 'Latn'],
        // 'en_NL' => ['name' => 'English (Netherlands)', 'native' => 'English (Netherlands)', 'script' => 'Latn'],
        // 'en_NZ' => ['name' => 'English (New Zealand)', 'native' => 'English (New Zealand)', 'script' => 'Latn'],
        // 'en_NG' => ['name' => 'English (Nigeria)', 'native' => 'English (Nigeria)', 'script' => 'Latn'],
        // 'en_NU' => ['name' => 'English (Niue)', 'native' => 'English (Niue)', 'script' => 'Latn'],
        // 'en_NF' => ['name' => 'English (Norfolk Island)', 'native' => 'English (Norfolk Island)', 'script' => 'Latn'],
        // 'en_MP' => ['name' => 'English (Northern Mariana Islands)', 'native' => 'English (Northern Mariana Islands)', 'script' => 'Latn'],
        // 'en_PK' => ['name' => 'English (Pakistan)', 'native' => 'English (Pakistan)', 'script' => 'Latn'],
        // 'en_PW' => ['name' => 'English (Palau)', 'native' => 'English (Palau)', 'script' => 'Latn'],
        // 'en_PG' => ['name' => 'English (Papua New Guinea)', 'native' => 'English (Papua New Guinea)', 'script' => 'Latn'],
        // 'en_PN' => ['name' => 'English (Pitcairn Islands)', 'native' => 'English (Pitcairn Islands)', 'script' => 'Latn'],
        // 'en_PR' => ['name' => 'English (Puerto Rico)', 'native' => 'English (Puerto Rico)', 'script' => 'Latn'],
        // 'en_PH' => ['name' => 'English (Philippines)', 'native' => 'English (Philippines)', 'script' => 'Latn'],
        // 'en_RW' => ['name' => 'English (Rwanda)', 'native' => 'English (Rwanda)', 'script' => 'Latn'],
        // 'en_KN' => ['name' => 'English (Saint Kitts and Nevis)', 'native' => 'English (Saint Kitts and Nevis)', 'script' => 'Latn'],
        // 'en_LC' => ['name' => 'English (Saint Lucia)', 'native' => 'English (Saint Lucia)', 'script' => 'Latn'],
        // 'en_VC' => ['name' => 'English (Saint Vincent and the Grenadines)', 'native' => 'English (Saint Vincent and the Grenadines)', 'script' => 'Latn'],
        // 'en_WS' => ['name' => 'English (Samoa)', 'native' => 'English (Samoa)', 'script' => 'Latn'],
        // 'en_SC' => ['name' => 'English (Seychelles)', 'native' => 'English (Seychelles)', 'script' => 'Latn'],
        // 'en_SL' => ['name' => 'English (Sierra Leone)', 'native' => 'English (Sierra Leone)', 'script' => 'Latn'],
        // 'en_SG' => ['name' => 'English (Singapore)', 'native' => 'English (Singapore)', 'script' => 'Latn'],
        // 'en_SX' => ['name' => 'English (Sint Maarten)', 'native' => 'English (Sint Maarten)', 'script' => 'Latn'],
        // 'en_SI' => ['name' => 'English (Slovenia)', 'native' => 'English (Slovenia)', 'script' => 'Latn'],
        // 'en_SB' => ['name' => 'English (Solomon Islands)', 'native' => 'English (Solomon Islands)', 'script' => 'Latn'],
        // 'en_ZA' => ['name' => 'English (South Africa)', 'native' => 'English (South Africa)', 'script' => 'Latn'],
        // 'en_SS' => ['name' => 'English (South Sudan)', 'native' => 'English (South Sudan)', 'script' => 'Latn'],
        // 'en_SH' => ['name' => 'English (St. Helena)', 'native' => 'English (St. Helena)', 'script' => 'Latn'],
        // 'en_SD' => ['name' => 'English (Sudan)', 'native' => 'English (Sudan)', 'script' => 'Latn'],
        // 'en_SZ' => ['name' => 'English (Swaziland)', 'native' => 'English (Swaziland)', 'script' => 'Latn'],
        // 'en_SE' => ['name' => 'English (Sweden)', 'native' => 'English (Sweden)', 'script' => 'Latn'],
        // 'en_CH' => ['name' => 'English (Switzerland)', 'native' => 'English (Switzerland)', 'script' => 'Latn'],
        // 'en_TZ' => ['name' => 'English (Tanzania)', 'native' => 'English (Tanzania)', 'script' => 'Latn'],
        // 'en_TK' => ['name' => 'English (Tokelau)', 'native' => 'English (Tokelau)', 'script' => 'Latn'],
        // 'en_TO' => ['name' => 'English (Tonga)', 'native' => 'English (Tonga)', 'script' => 'Latn'],
        // 'en_TT' => ['name' => 'English (Trinidad and Tobago)', 'native' => 'English (Trinidad and Tobago)', 'script' => 'Latn'],
        // 'en_TC' => ['name' => 'English (Turks and Caicos Islands)', 'native' => 'English (Turks and Caicos Islands)', 'script' => 'Latn'],
        // 'en_TV' => ['name' => 'English (Tuvalu)', 'native' => 'English (Tuvalu)', 'script' => 'Latn'],
        // 'en_UG' => ['name' => 'English (Uganda)', 'native' => 'English (Uganda)', 'script' => 'Latn'],
        // 'en_AE' => ['name' => 'English (United Arab Emirates)', 'native' => 'English (United Arab Emirates)', 'script' => 'Latn'],
        // 'en_GB' => ['name' => 'English (United Kingdom)', 'native' => 'English (United Kingdom)', 'script' => 'Latn'],
        // 'en_US' => ['name' => 'English (United States)', 'native' => 'English (United States)', 'script' => 'Latn'],
        // 'en_UM' => ['name' => 'English (U.S. Minor Outlying Islands)', 'native' => 'English (U.S. Minor Outlying Islands)', 'script' => 'Latn'],
        // 'en_VI' => ['name' => 'English (U.S. Virgin Islands)', 'native' => 'English (U.S. Virgin Islands)', 'script' => 'Latn'],
        // 'en_VU' => ['name' => 'English (Vanuatu)', 'native' => 'English (Vanuatu)', 'script' => 'Latn'],
        // 'en_001' => ['name' => 'English (World)', 'native' => 'English (World)', 'script' => 'Latn'],
        // 'en_ZM' => ['name' => 'English (Zambia)', 'native' => 'English (Zambia)', 'script' => 'Latn'],
        // 'en_ZW' => ['name' => 'English (Zimbabwe)', 'native' => 'English (Zimbabwe)', 'script' => 'Latn'],
        // 'eo' => ['name' => 'Esperanto', 'native' => 'Esperanto', 'script' => 'Latn'],
        // 'eo_001' => ['name' => 'Esperanto (World)', 'native' => 'Esperanto (World)', 'script' => 'Latn'],
        // 'et' => ['name' => 'Estonian', 'native' => 'Eesti', 'script' => 'Latn'],
        // 'et_EE' => ['name' => 'Estonian (Estonia)', 'native' => 'Eesti (Eesti)', 'script' => 'Latn'],
        // 'ee' => ['name' => 'Ewe', 'native' => 'Eʋegbe', 'script' => 'Latn'],
        // 'ee_GH' => ['name' => 'Ewe (Ghana)', 'native' => 'eʋegbe (Ghana)', 'script' => 'Latn'],
        // 'ee_TG' => ['name' => 'Ewe (Togo)', 'native' => 'eʋegbe (Togo)', 'script' => 'Latn'],
        // 'ewo' => ['name' => 'Ewondo', 'native' => 'ewondo', 'script' => 'Latn'],
        // 'ewo_CM' => ['name' => 'Ewondo (Cameroon)', 'native' => 'ewondo (Cameroun)', 'script' => 'Latn'],
        // 'fo' => ['name' => 'Faroese', 'native' => 'føroyskt', 'script' => 'Latn'],
        // 'fo_DK' => ['name' => 'Faroese (Denmark)', 'native' => 'føroyskt (Danmark)', 'script' => 'Latn'],
        // 'fo_FO' => ['name' => 'Faroese (Faroe Islands)', 'native' => 'føroyskt (Føroyar)', 'script' => 'Latn'],
        // 'fil' => ['name' => 'Filipino', 'native' => 'Filipino', 'script' => 'Latn'],
        // 'fil_PH' => ['name' => 'Filipino (Philippines)', 'native' => 'Filipino (Pilipinas)', 'script' => 'Latn'],
        // 'fi' => ['name' => 'Finnish', 'native' => 'suomi', 'script' => 'Latn'],
        // 'fi_FI' => ['name' => 'Finnish (Finland)', 'native' => 'suomi (Suomi)', 'script' => 'Latn'],
        // 'fr' => ['name' => 'French', 'native' => 'français', 'script' => 'Latn'],
        // 'fr_DZ' => ['name' => 'French (Algeria)', 'native' => 'français (Algérie)', 'script' => 'Latn'],
        // 'fr_BE' => ['name' => 'French (Belgium)', 'native' => 'français (Belgique)', 'script' => 'Latn'],
        // 'fr_BJ' => ['name' => 'French (Benin)', 'native' => 'français (Bénin)', 'script' => 'Latn'],
        // 'fr_BF' => ['name' => 'French (Burkina Faso)', 'native' => 'français (Burkina Faso)', 'script' => 'Latn'],
        // 'fr_BI' => ['name' => 'French (Burundi)', 'native' => 'français (Burundi)', 'script' => 'Latn'],
        // 'fr_CM' => ['name' => 'French (Cameroon)', 'native' => 'français (Cameroun)', 'script' => 'Latn'],
        // 'fr_CA' => ['name' => 'French (Canada)', 'native' => 'français (Canada)', 'script' => 'Latn'],
        // 'fr_029' => ['name' => 'French (Caribbean)', 'native' => 'français (Caraïbes)', 'script' => 'Latn'],
        // 'fr_CF' => ['name' => 'French (Central African Republic)', 'native' => 'français (République centrafricaine)', 'script' => 'Latn'],
        // 'fr_TD' => ['name' => 'French (Chad)', 'native' => 'français (Tchad)', 'script' => 'Latn'],
        // 'fr_KM' => ['name' => 'French (Comoros)', 'native' => 'français (Comores)', 'script' => 'Latn'],
        // 'fr_CG' => ['name' => 'French (Congo - Brazzaville)', 'native' => 'français (Congo-Brazzaville)', 'script' => 'Latn'],
        // 'fr_CD' => ['name' => 'French (Congo - Kinshasa)', 'native' => 'français (Congo-Kinshasa)', 'script' => 'Latn'],
        // 'fr_CI' => ['name' => 'French (Côte d’Ivoire)', 'native' => 'français (Côte d’Ivoire)', 'script' => 'Latn'],
        // 'fr_DJ' => ['name' => 'French (Djibouti)', 'native' => 'français (Djibouti)', 'script' => 'Latn'],
        // 'fr_GQ' => ['name' => 'French (Equatorial Guinea)', 'native' => 'français (Guinée équatoriale)', 'script' => 'Latn'],
        // 'fr_FR' => ['name' => 'French (France)', 'native' => 'français (France)', 'script' => 'Latn'],
        // 'fr_GF' => ['name' => 'French (French Guiana)', 'native' => 'français (Guyane française)', 'script' => 'Latn'],
        // 'fr_PF' => ['name' => 'French (French Polynesia)', 'native' => 'français (Polynésie française)', 'script' => 'Latn'],
        // 'fr_GA' => ['name' => 'French (Gabon)', 'native' => 'français (Gabon)', 'script' => 'Latn'],
        // 'fr_GP' => ['name' => 'French (Guadeloupe)', 'native' => 'français (Guadeloupe)', 'script' => 'Latn'],
        // 'fr_GN' => ['name' => 'French (Guinea)', 'native' => 'français (Guinée)', 'script' => 'Latn'],
        // 'fr_HT' => ['name' => 'French (Haiti)', 'native' => 'français (Haïti)', 'script' => 'Latn'],
        // 'fr_LU' => ['name' => 'French (Luxembourg)', 'native' => 'français (Luxembourg)', 'script' => 'Latn'],
        // 'fr_MG' => ['name' => 'French (Madagascar)', 'native' => 'français (Madagascar)', 'script' => 'Latn'],
        // 'fr_ML' => ['name' => 'French (Mali)', 'native' => 'français (Mali)', 'script' => 'Latn'],
        // 'fr_MQ' => ['name' => 'French (Martinique)', 'native' => 'français (Martinique)', 'script' => 'Latn'],
        // 'fr_MR' => ['name' => 'French (Mauritania)', 'native' => 'français (Mauritanie)', 'script' => 'Latn'],
        // 'fr_MU' => ['name' => 'French (Mauritius)', 'native' => 'français (Maurice)', 'script' => 'Latn'],
        // 'fr_YT' => ['name' => 'French (Mayotte)', 'native' => 'français (Mayotte)', 'script' => 'Latn'],
        // 'fr_MA' => ['name' => 'French (Morocco)', 'native' => 'français (Maroc)', 'script' => 'Latn'],
        // 'fr_NC' => ['name' => 'French (New Caledonia)', 'native' => 'français (Nouvelle-Calédonie)', 'script' => 'Latn'],
        // 'fr_NE' => ['name' => 'French (Niger)', 'native' => 'français (Niger)', 'script' => 'Latn'],
        // 'fr_MC' => ['name' => 'French (Monaco)', 'native' => 'français (Monaco)', 'script' => 'Latn'],
        // 'fr_RE' => ['name' => 'French (Réunion)', 'native' => 'français (Réunion)', 'script' => 'Latn'],
        // 'fr_RW' => ['name' => 'French (Rwanda)', 'native' => 'français (Rwanda)', 'script' => 'Latn'],
        // 'fr_BL' => ['name' => 'French (Saint Barthélemy)', 'native' => 'français (Saint-Barthélemy)', 'script' => 'Latn'],
        // 'fr_MF' => ['name' => 'French (Saint Martin)', 'native' => 'français (Saint-Martin)', 'script' => 'Latn'],
        // 'fr_PM' => ['name' => 'French (Saint Pierre and Miquelon)', 'native' => 'français (Saint-Pierre-et-Miquelon)', 'script' => 'Latn'],
        // 'fr_SN' => ['name' => 'French (Senegal)', 'native' => 'français (Sénégal)', 'script' => 'Latn'],
        // 'fr_SC' => ['name' => 'French (Seychelles)', 'native' => 'français (Seychelles)', 'script' => 'Latn'],
        // 'fr_CH' => ['name' => 'French (Switzerland)', 'native' => 'français (Suisse)', 'script' => 'Latn'],
        // 'fr_SY' => ['name' => 'French (Syria)', 'native' => 'français (Syrie)', 'script' => 'Latn'],
        // 'fr_TG' => ['name' => 'French (Togo)', 'native' => 'français (Togo)', 'script' => 'Latn'],
        // 'fr_TN' => ['name' => 'French (Tunisia)', 'native' => 'français (Tunisie)', 'script' => 'Latn'],
        // 'fr_VU' => ['name' => 'French (Vanuatu)', 'native' => 'français (Vanuatu)', 'script' => 'Latn'],
        // 'fr_WF' => ['name' => 'French (Wallis and Futuna)', 'native' => 'français (Wallis-et-Futuna)', 'script' => 'Latn'],
        // 'fy' => ['name' => 'Western Frisian', 'native' => 'Frysk', 'script' => 'Latn'],
        // 'fy_NL' => ['name' => 'Western Frisian (Netherlands)', 'native' => 'Frysk (Nederlân)', 'script' => 'Latn'],
        // 'fur' => ['name' => 'Friulian', 'native' => 'furlan', 'script' => 'Latn'],
        // 'fur_IT' => ['name' => 'Friulian (Italy)', 'native' => 'furlan (Italia)', 'script' => 'Latn'],
        // 'ff' => ['name' => 'Fulah', 'native' => 'Fulfulde', 'script' => 'Latn'],
        // 'ff_Latn' => ['name' => 'Fulah', 'native' => 'Fulfulde', 'script' => 'Latn'],
        // 'ff_Latn_BF' => ['name' => 'Fulah (Burkina Faso)', 'native' => 'Fulfulde (Burkina Faso)', 'script' => 'Latn'],
        // 'ff_CM' => ['name' => 'Fulah (Cameroon)', 'native' => 'Fulfulde (Kàmɛ̀rûn)', 'script' => 'Latn'],
        // 'ff_Latn_CM' => ['name' => 'Fulah (Cameroon)', 'native' => 'Fulfulde (Kàmɛ̀rûn)', 'script' => 'Latn'],
        // 'ff_Latn_GM' => ['name' => 'Fulah (Gambia)', 'native' => 'Fulfulde (Gàmbià)', 'script' => 'Latn'],
        // 'ff_Latn_GH' => ['name' => 'Fulah (Ghana)', 'native' => 'Fulfulde (Ghana)', 'script' => 'Latn'],
        // 'ff_GN' => ['name' => 'Fulah (Guinea)', 'native' => 'Fulfulde (Guinée)', 'script' => 'Latn'],
        // 'ff_Latn_GN' => ['name' => 'Fulah (Guinea)', 'native' => 'Fulfulde (Guinée)', 'script' => 'Latn'],
        // 'ff_Latn_GW' => ['name' => 'Fulah (Guinea-Bissau)', 'native' => 'Fulfulde (Guiné Bissau)', 'script' => 'Latn'],
        // 'ff_Latn_LR' => ['name' => 'Fulah (Liberia)', 'native' => 'Fulfulde (Laibya)', 'script' => 'Latn'],
        // 'ff_MR' => ['name' => 'Fulah (Mauritania)', 'native' => 'Fulfulde (Muritaniya)', 'script' => 'Latn'],
        // 'ff_Latn_MR' => ['name' => 'Fulah (Mauritania)', 'native' => 'Fulfulde (Muritaniya)', 'script' => 'Latn'],
        // 'ff_Latn_NE' => ['name' => 'Fulah (Niger)', 'native' => 'Fulfulde (Nižɛ̌ɛ̌r)', 'script' => 'Latn'],
        // 'ff_NG' => ['name' => 'Fulah (Nigeria)', 'native' => 'Fulfulde (Najeriya)', 'script' => 'Latn'],
        // 'ff_Latn_NG' => ['name' => 'Fulah (Nigeria)', 'native' => 'Fulfulde (Najeriya)', 'script' => 'Latn'],
        // 'ff_Latn_SN' => ['name' => 'Fulah (Senegal)', 'native' => 'Fulfulde (Senegal)', 'script' => 'Latn'],
        // 'ff_Latn_SL' => ['name' => 'Fulah (Sierra Leone)', 'native' => 'Fulfulde (Sera Liyɔ̌n)', 'script' => 'Latn'],
        // 'gl' => ['name' => 'Galician', 'native' => 'galego', 'script' => 'Latn'],
        // 'gl_ES' => ['name' => 'Galician (Spain)', 'native' => 'galego (España)', 'script' => 'Latn'],
        // 'lg' => ['name' => 'Ganda', 'native' => 'Luganda', 'script' => 'Latn'],
        // 'lg_UG' => ['name' => 'Ganda (Uganda)', 'native' => 'Luganda (Yuganda)', 'script' => 'Latn'],
        // 'ka' => ['name' => 'Georgian', 'native' => 'ქართული', 'script' => 'Geor'],
        // 'ka_GE' => ['name' => 'Georgian (Georgia)', 'native' => 'ქართული (საქართველო)', 'script' => 'Geor'],
        // 'de' => ['name' => 'German', 'native' => 'Deutsch', 'script' => 'Latn'],
        // 'de_AT' => ['name' => 'German (Austria)', 'native' => 'Deutsch (Österreich)', 'script' => 'Latn'],
        // 'de_BE' => ['name' => 'German (Belgium)', 'native' => 'Deutsch (Belgien)', 'script' => 'Latn'],
        // 'de_DE' => ['name' => 'German (Germany)', 'native' => 'Deutsch (Deutschland)', 'script' => 'Latn'],
        // 'de_IT' => ['name' => 'German (Italy)', 'native' => 'Deutsch (Italien)', 'script' => 'Latn'],
        // 'de_LI' => ['name' => 'German (Liechtenstein)', 'native' => 'Deutsch (Liechtenstein)', 'script' => 'Latn'],
        // 'de_LU' => ['name' => 'German (Luxembourg)', 'native' => 'Deutsch (Luxemburg)', 'script' => 'Latn'],
        // 'de_CH' => ['name' => 'German (Switzerland)', 'native' => 'Deutsch (Schweiz)', 'script' => 'Latn'],
        // 'el' => ['name' => 'Greek', 'native' => 'Ελληνικά', 'script' => 'Grek'],
        // 'el_CY' => ['name' => 'Greek (Cyprus)', 'native' => 'Ελληνικά (Κύπρος)', 'script' => 'Grek'],
        // 'el_GR' => ['name' => 'Greek (Greece)', 'native' => 'Ελληνικά (Ελλάδα)', 'script' => 'Grek'],
        // 'kl' => ['name' => 'Greenlandic', 'native' => 'kalaallisut', 'script' => 'Latn'],
        // 'kl_GL' => ['name' => 'Greenlandic (Greenland)', 'native' => 'kalaallisut (Kalaallit Nunaat)', 'script' => 'Latn'],
        // 'gn' => ['name' => 'Guaraní', 'native' => 'Avañe’ẽ', 'script' => 'Latn'],
        // 'gn_PY' => ['name' => 'Guaraní (Paraguay)', 'native' => 'Avañe’ẽ (Paraguái)', 'script' => 'Latn'],
        // 'gu' => ['name' => 'Gujarati', 'native' => 'ગુજરાતી', 'script' => 'Gujr'],
        // 'gu_IN' => ['name' => 'Gujarati (India)', 'native' => 'ગુજરાતી (ભારત)', 'script' => 'Gujr'],
        // 'guz' => ['name' => 'Gusii', 'native' => 'Ekegusii', 'script' => 'Latn'],
        // 'guz_KE' => ['name' => 'Gusii (Kenya)', 'native' => 'Ekegusii (Kenia)', 'script' => 'Latn'],
        // 'ha' => ['name' => 'Hausa', 'native' => 'Hausa', 'script' => 'Latn'],
        // 'ha_Latn' => ['name' => 'Hausa', 'native' => 'Hausa', 'script' => 'Latn'],
        // 'ha_Latn_GH' => ['name' => 'Hausa (Ghana)', 'native' => 'Hausa (Gana)', 'script' => 'Latn'],
        // 'ha_Latn_NE' => ['name' => 'Hausa (Niger)', 'native' => 'Hausa (Nijar)', 'script' => 'Latn'],
        // 'ha_Latn_NG' => ['name' => 'Hausa (Nigeria)', 'native' => 'Hausa (Najeriya)', 'script' => 'Latn'],
        // 'haw' => ['name' => 'Hawaiian', 'native' => 'Hawaiʻi', 'script' => 'Latn'],
        // 'haw_US' => ['name' => 'Hawaiian (United States)', 'native' => 'Hawaiʻi (ʻAmelika Hui Pū ʻIa)', 'script' => 'Latn'],
        // 'hi' => ['name' => 'Hindi', 'native' => 'हिन्दी', 'script' => 'Deva'],
        // 'hi_IN' => ['name' => 'Hindi (India)', 'native' => 'हिन्दी (भारत)', 'script' => 'Deva'],
        // 'hu' => ['name' => 'Hungarian', 'native' => 'magyar', 'script' => 'Latn'],
        // 'hu_HU' => ['name' => 'Hungarian (Hungary)', 'native' => 'magyar (Magyarország)', 'script' => 'Latn'],
        // 'is' => ['name' => 'Icelandic', 'native' => 'íslenska', 'script' => 'Latn'],
        // 'is_IS' => ['name' => 'Icelandic (Iceland)', 'native' => 'íslenska (Ísland)', 'script' => 'Latn'],
        // 'ig' => ['name' => 'Igbo', 'native' => 'Igbo', 'script' => 'Latn'],
        // 'ig_NG' => ['name' => 'Igbo (Nigeria)', 'native' => 'Igbo (Nigeria)', 'script' => 'Latn'],
        // 'id' => ['name' => 'Indonesian', 'native' => 'Bahasa Indonesia', 'script' => 'Latn'],
        // 'id_ID' => ['name' => 'Indonesian (Indonesia)', 'native' => 'Bahasa Indonesia (Indonesia)', 'script' => 'Latn'],
        // 'ia' => ['name' => 'Interlingua', 'native' => 'Interlingua', 'script' => 'Latn'],
        // 'ia_FR' => ['name' => 'Interlingua (France)', 'native' => 'Interlingua (Francie)', 'script' => 'Latn'],
        // 'ia_001' => ['name' => 'Interlingua (World)', 'native' => 'Interlingua (Mundo)', 'script' => 'Latn'],
        // 'iu' => ['name' => 'Inuktitut', 'native' => 'ᐃᓄᒃᑎᑐᑦ', 'script' => 'Latn'],
        // 'iu_Latn' => ['name' => 'Inuktitut', 'native' => 'ᐃᓄᒃᑎᑐᑦ', 'script' => 'Latn'],
        // 'iu_Latn_CA' => ['name' => 'Inuktitut (Canada)', 'native' => 'ᐃᓄᒃᑎᑐᑦ (Kanatami)', 'script' => 'Latn'],
        // 'iu_Cans' => ['name' => 'Inuktitut', 'native' => 'ᐃᓄᒃᑎᑐᑦ', 'script' => 'Cans'],
        // 'iu_Cans_CA' => ['name' => 'Inuktitut (Canada)', 'native' => 'ᐃᓄᒃᑎᑐᑦ (Kanatami)', 'script' => 'Cans'],
        // 'ga' => ['name' => 'Irish', 'native' => 'Gaeilge', 'script' => 'Latn'],
        // 'ga_IE' => ['name' => 'Irish (Ireland)', 'native' => 'Gaeilge (Éire)', 'script' => 'Latn'],
        // 'it' => ['name' => 'Italian', 'native' => 'italiano', 'script' => 'Latn'],
        // 'it_IT' => ['name' => 'Italian (Italy)', 'native' => 'italiano (Italia)', 'script' => 'Latn'],
        // 'it_SM' => ['name' => 'Italian (San Marino)', 'native' => 'italiano (San Marino)', 'script' => 'Latn'],
        // 'it_CH' => ['name' => 'Italian (Switzerland)', 'native' => 'italiano (Svizzera)', 'script' => 'Latn'],
        // 'it_VA' => ['name' => 'Italian (Vatican City)', 'native' => 'italiano (Città del Vaticano)', 'script' => 'Latn'],
        // 'ja' => ['name' => 'Japanese', 'native' => '日本語', 'script' => 'Jpan'],
        // 'ja_JP' => ['name' => 'Japanese (Japan)', 'native' => '日本語 (日本)', 'script' => 'Jpan'],
        // 'jv' => ['name' => 'Javanese', 'native' => 'Basa Jawa', 'script' => 'Latn'],
        // 'jv_Latn' => ['name' => 'Javanese', 'native' => 'Basa Jawa', 'script' => 'Latn'],
        // 'jv_Latn_ID' => ['name' => 'Javanese (Indonesia)', 'native' => 'Basa Jawa (Indonesia)', 'script' => 'Latn'],
        // 'dyo' => ['name' => 'Jola-Fonyi', 'native' => 'Joola', 'script' => 'Latn'],
        // 'dyo_SN' => ['name' => 'Jola-Fonyi (Senegal)', 'native' => 'Joola (Senegal)', 'script' => 'Latn'],
        // 'kea' => ['name' => 'Kabuverdianu', 'native' => 'Kabuverdianu', 'script' => 'Latn'],
        // 'kea_CV' => ['name' => 'Kabuverdianu (Cabo Verde)', 'native' => 'Kabuverdianu (Kabu Verdi)', 'script' => 'Latn'],
        // 'kab' => ['name' => 'Kabyle', 'native' => 'Taqbaylit', 'script' => 'Latn'],
        // 'kab_DZ' => ['name' => 'Kabyle (Algeria)', 'native' => 'Kabyle (Algeria)', 'script' => 'Latn'],
        // 'kkj' => ['name' => 'Kako (Cameroon)', 'native' => 'Kako (Cameroon)', 'script' => 'Latn'],
        // 'kkj_CM' => ['name' => 'Kako (Cameroon)', 'native' => 'Kako (Cameroon)', 'script' => 'Latn'],
        // 'kln' => ['name' => 'Kalenjin (Kenya)', 'native' => 'Kalenjin (Kenya)', 'script' => 'Latn'],
        // 'kln_KE' => ['name' => 'Kalenjin (Kenya)', 'native' => 'Kalenjin (Kenya)', 'script' => 'Latn'],
        // 'kam' => ['name' => 'Kamba (Kenya)', 'native' => 'Kamba (Kenya)', 'script' => 'Latn'],
        // 'kam_KE' => ['name' => 'Kamba (Kenya)', 'native' => 'Kamba (Kenya)', 'script' => 'Latn'],
        // 'kn' => ['name' => 'Kannada (India)', 'native' => 'ಕನ್ನಡ (ಭಾರತ)', 'script' => 'Knda'],
        // 'kn_IN' => ['name' => 'Kannada (India)', 'native' => 'ಕನ್ನಡ (ಭಾರತ)', 'script' => 'Knda'],
        // 'kr_Latn_NG' => ['name' => 'Koro (Nigeria)', 'native' => 'Koro (Nigeria)', 'script' => 'Latn'],
        // 'ks' => ['name' => 'Kashmiri', 'native' => 'कश्मीरी', 'script' => 'Arab'],
        // 'ks_Arab' => ['name' => 'Kashmiri', 'native' => 'كشميري', 'script' => 'Arab'],
        // 'ks_Arab_IN' => ['name' => 'Kashmiri', 'native' => 'كشميري', 'script' => 'Arab'],
        // 'ks_Deva_IN' => ['name' => 'Kashmiri', 'native' => 'कश्मीरी', 'script' => 'Deva'],
        // 'kk' => ['name' => 'Kazakh', 'native' => 'қазақ тілі', 'script' => 'Cyrl'],
        // 'kk_KZ' => ['name' => 'Kazakh', 'native' => 'қазақ тілі', 'script' => 'Cyrl'],
        // 'km' => ['name' => 'Khmer', 'native' => 'ខ្មែរ', 'script' => 'Khmr'],
        // 'km_KH' => ['name' => 'Khmer', 'native' => 'ខ្មែរ', 'script' => 'Khmr'],
        // 'quc' => ['name' => 'Kʼicheʼ', 'native' => 'Kʼicheʼ', 'script' => 'Latn'],
        // 'quc_Latn_GT' => ['name' => 'Kʼicheʼ', 'native' => 'Kʼicheʼ', 'script' => 'Latn'],
        // 'ki' => ['name' => 'Kikuyu', 'native' => 'Kikuyu', 'script' => 'Latn'],
        // 'ki_KE' => ['name' => 'Kikuyu', 'native' => 'Kikuyu', 'script' => 'Latn'],
        // 'rw' => ['name' => 'Kinyarwanda', 'native' => 'Kinyarwanda', 'script' => 'Latn'],
        // 'rw_RW' => ['name' => 'Kinyarwanda', 'native' => 'Kinyarwanda', 'script' => 'Latn'],
        // 'sw' => ['name' => 'Kiswahili', 'native' => 'Kiswahili', 'script' => 'Latn'],
        // 'sw_KE' => ['name' => 'Kiswahili', 'native' => 'Kiswahili', 'script' => 'Latn'],
        // 'sw_TZ' => ['name' => 'Kiswahili', 'native' => 'Kiswahili', 'script' => 'Latn'],
        // 'sw_UG' => ['name' => 'Kiswahili', 'native' => 'Kiswahili', 'script' => 'Latn'],
        // 'kok' => ['name' => 'Konkani', 'native' => 'कोंकणी', 'script' => 'Deva'],
        // 'kok_IN' => ['name' => 'Konkani', 'native' => 'कोंकणी', 'script' => 'Deva'],
        // 'ko' => ['name' => 'Korean', 'native' => '한국어', 'script' => 'Hang'],
        // 'ko_KR' => ['name' => 'Korean (South Korea)', 'native' => '한국어 (대한민국)', 'script' => 'Hang'],
        // 'ko_KP' => ['name' => 'Korean (North Korea)', 'native' => '한국어 (조선 민주주의 인민 공화국)', 'script' => 'Hang'],
        // 'khq' => ['name' => 'Koyra Chiini', 'native' => 'Koyra ciini', 'script' => 'Latn'],
        // 'khq_ML' => ['name' => 'Koyra Chiini (Mali)', 'native' => 'Koyra ciini (Maali)', 'script' => 'Latn'],
        // 'ses' => ['name' => 'Koyraboro Senni', 'native' => 'Koyraboro senni', 'script' => 'Latn'],
        // 'ses_ML' => ['name' => 'Koyraboro Senni (Mali)', 'native' => 'Koyraboro senni (Maali)', 'script' => 'Latn'],
        // 'nmg' => ['name' => 'Kwasio', 'native' => 'Nmgong', 'script' => 'Latn'],
        // 'nmg_CM' => ['name' => 'Kwasio (Cameroon)', 'native' => 'Nmgong (Kamerun)', 'script' => 'Latn'],
        // 'ky' => ['name' => 'Kyrgyz', 'native' => 'Кыргызча', 'script' => 'Cyrl'],
        // 'ky_KG' => ['name' => 'Kyrgyz (Kyrgyzstan)', 'native' => 'Кыргызча (Кыргызстан)', 'script' => 'Cyrl'],
        // 'ku_Arab_IR' => ['name' => 'Kurdish (Arabic, Iran)', 'native' => 'کوردی (فارسی)', 'script' => 'Arab'],
        // 'lkt' => ['name' => 'Lakota', 'native' => 'Lakȟólʼiyapi', 'script' => 'Latn'],
        // 'lkt_US' => ['name' => 'Lakota (United States)', 'native' => 'Lakȟólʼiyapi (Mílahaŋska Tȟamákȟočhe)', 'script' => 'Latn'],
        // 'lag' => ['name' => 'Langi', 'native' => 'Kɨlaangi', 'script' => 'Latn'],
        // 'lag_TZ' => ['name' => 'Langi (Tanzania)', 'native' => 'Kɨlaangi (Taansanía)', 'script' => 'Latn'],
        // 'lo' => ['name' => 'Lao', 'native' => 'ລາວ', 'script' => 'Laoo'],
        // 'lo_LA' => ['name' => 'Lao (Laos)', 'native' => 'ລາວ (ລາວ)', 'script' => 'Laoo'],
        // 'la_VA' => ['name' => 'Latin (Vatican City)', 'native' => 'Latine (Civitas Vaticana)', 'script' => 'Latn'],
        // 'lv' => ['name' => 'Latvian', 'native' => 'latviešu', 'script' => 'Latn'],
        // 'lv_LV' => ['name' => 'Latvian (Latvia)', 'native' => 'latviešu (Latvija)', 'script' => 'Latn'],
        // 'ln' => ['name' => 'Lingala', 'native' => 'Lingála', 'script' => 'Latn'],
        // 'ln_AO' => ['name' => 'Lingala (Angola)', 'native' => 'Lingála (Angóla)', 'script' => 'Latn'],
        // 'ln_CF' => ['name' => 'Lingala (Central African Republic)', 'native' => 'Lingála (République centrafricaine)', 'script' => 'Latn'],
        // 'ln_CG' => ['name' => 'Lingala (Congo - Brazzaville)', 'native' => 'Lingála (Kongo - Brazzaville)', 'script' => 'Latn'],
        // 'ln_CD' => ['name' => 'Lingala (Congo - Kinshasa)', 'native' => 'Lingála (Jamhuri ya Kidemokrasia ya Kongo)', 'script' => 'Latn'],
        // 'lt' => ['name' => 'Lithuanian', 'native' => 'lietuvių', 'script' => 'Latn'],
        // 'lt_LT' => ['name' => 'Lithuanian (Lithuania)', 'native' => 'lietuvių (Lietuva)', 'script' => 'Latn'],
        // 'nds' => ['name' => 'Low German', 'native' => 'Plattdüütsch', 'script' => 'Latn'],
        // 'nds_DE' => ['name' => 'Low German (Germany)', 'native' => 'Plattdüütsch (Düütschland)', 'script' => 'Latn'],
        // 'nds_NL' => ['name' => 'Low German (Netherlands)', 'native' => 'Plattdüütsch (Nedderlannen)', 'script' => 'Latn'],
        // 'dsb' => ['name' => 'Lower Sorbian', 'native' => 'dolnoserbšćina', 'script' => 'Latn'],
        // 'dsb_DE' => ['name' => 'Lower Sorbian (Germany)', 'native' => 'dolnoserbšćina (Němska)', 'script' => 'Latn'],
        // 'lu' => ['name' => 'Luba-Katanga', 'native' => 'Tshiluba', 'script' => 'Latn'],
        // 'lu_CD' => ['name' => 'Luba-Katanga (Congo - Kinshasa)', 'native' => 'Tshiluba (Jamhuri ya Kidemokrasia ya Kongo)', 'script' => 'Latn'],
        // 'luo' => ['name' => 'Luo', 'native' => 'Dholuo', 'script' => 'Latn'],
        // 'luo_KE' => ['name' => 'Luo (Kenya)', 'native' => 'Dholuo (Kenya)', 'script' => 'Latn'],
        // 'lb' => ['name' => 'Luxembourgish', 'native' => 'Lëtzebuergesch', 'script' => 'Latn'],
        // 'lb_LU' => ['name' => 'Luxembourgish (Luxembourg)', 'native' => 'Lëtzebuergesch (Lëtzebuerg)', 'script' => 'Latn'],
        // 'luy' => ['name' => 'Luyia', 'native' => 'Luluhia', 'script' => 'Latn'],
        // 'luy_KE' => ['name' => 'Luyia (Kenya)', 'native' => 'Luluhia (Kenya)', 'script' => 'Latn'],
        // 'mk' => ['name' => 'Macedonian', 'native' => 'македонски', 'script' => 'Cyrl'],
        // 'mk_MK' => ['name' => 'Macedonian (North Macedonia)', 'native' => 'македонски (Северна Македонија)', 'script' => 'Cyrl'],
        // 'jmc' => ['name' => 'Machame', 'native' => 'Kimachame', 'script' => 'Latn'],
        // 'jmc_TZ' => ['name' => 'Machame (Tanzania)', 'native' => 'Kimachame (Tanzania)', 'script' => 'Latn'],
        // 'mgh' => ['name' => 'Makhuwa-Meetto', 'native' => 'Makua', 'script' => 'Latn'],
        // 'mgh_MZ' => ['name' => 'Makhuwa-Meetto (Mozambique)', 'native' => 'Makua (Moçambique)', 'script' => 'Latn'],
        // 'kde' => ['name' => 'Makonde', 'native' => 'Chimakonde', 'script' => 'Latn'],
        // 'kde_TZ' => ['name' => 'Makonde (Tanzania)', 'native' => 'Chimakonde (Tanzania)', 'script' => 'Latn'],
        // 'mg' => ['name' => 'Malagasy', 'native' => 'Malagasy', 'script' => 'Latn'],
        // 'mg_MG' => ['name' => 'Malagasy (Madagascar)', 'native' => 'Malagasy (Madagasikara)', 'script' => 'Latn'],
        // 'ms' => ['name' => 'Malay', 'native' => 'Bahasa Melayu', 'script' => 'Latn'],
        // 'ms_BN' => ['name' => 'Malay (Brunei)', 'native' => 'Bahasa Melayu (Brunei)', 'script' => 'Latn'],
        // 'ms_MY' => ['name' => 'Malay (Malaysia)', 'native' => 'Bahasa Melayu (Malaysia)', 'script' => 'Latn'],
        // 'ml' => ['name' => 'Malayalam', 'native' => 'മലയാളം', 'script' => 'Mlym'],
        // 'ml_IN' => ['name' => 'Malayalam (India)', 'native' => 'മലയാളം (ഇന്തിയ)', 'script' => 'Mlym'],
        // 'mt' => ['name' => 'Maltese', 'native' => 'Malti', 'script' => 'Latn'],
        // 'mt_MT' => ['name' => 'Maltese (Malta)', 'native' => 'Malti (Malta)', 'script' => 'Latn'],
        // 'gv' => ['name' => 'Manx', 'native' => 'Gaelg', 'script' => 'Latn'],
        // 'gv_IM' => ['name' => 'Manx (Isle of Man)', 'native' => 'Gaelg (Ellan Vannin)', 'script' => 'Latn'],
        // 'mi' => ['name' => 'Maori', 'native' => 'Māori', 'script' => 'Latn'],
        // 'mi_NZ' => ['name' => 'Maori (New Zealand)', 'native' => 'Māori (Aotearoa)', 'script' => 'Latn'],
        // 'arn' => ['name' => 'Mapudungun', 'native' => 'Mapudungun', 'script' => 'Latn'],
        // 'arn_CL' => ['name' => 'Mapudungun (Chile)', 'native' => 'Mapudungun (Chile)', 'script' => 'Latn'],
        // 'mr' => ['name' => 'Marathi', 'native' => 'मराठी', 'script' => 'Deva'],
        // 'mr_IN' => ['name' => 'Marathi (India)', 'native' => 'मराठी (भारत)', 'script' => 'Deva'],
        // 'mas' => ['name' => 'Masai', 'native' => 'Maa', 'script' => 'Latn'],
        // 'mas_KE' => ['name' => 'Masai (Kenya)', 'native' => 'Maa (Kenya)', 'script' => 'Latn'],
        // 'mas_TZ' => ['name' => 'Masai (Tanzania)', 'native' => 'Maa (Tanzania)', 'script' => 'Latn'],
        // 'mzn_IR' => ['name' => 'Mazanderani', 'native' => 'مازندرانی', 'script' => 'Arab'],
        // 'mer' => ['name' => 'Meru', 'native' => 'Kĩmĩrũ', 'script' => 'Latn'],
        // 'mer_KE' => ['name' => 'Meru (Kenya)', 'native' => 'Kĩmĩrũ (Kenya)', 'script' => 'Latn'],
        // 'mgo' => ['name' => 'Metaʼ', 'native' => 'Metaʼ', 'script' => 'Latn'],
        // 'mgo_CM' => ['name' => 'Metaʼ (Cameroon)', 'native' => 'Metaʼ (Kamərún)', 'script' => 'Latn'],
        // 'moh' => ['name' => 'Mohawk', 'native' => 'Kanienʼkéha', 'script' => 'Latn'],
        // 'moh_CA' => ['name' => 'Mohawk (Canada)', 'native' => 'Kanienʼkéha (Kanáta)', 'script' => 'Latn'],
        // 'mn' => ['name' => 'Mongolian', 'native' => 'монгол', 'script' => 'Cyrl'],
        // 'mn_Cyrl' => ['name' => 'Mongolian (Cyrillic)', 'native' => 'монгол', 'script' => 'Cyrl'],
        // 'mn_MN' => ['name' => 'Mongolian (Mongolia)', 'native' => 'монгол (Монгол улс)', 'script' => 'Cyrl'],
        // 'mn_Mong' => ['name' => 'Mongolian (Traditional Mongolian)', 'native' => 'ᠮᠤᠨᠭᠭᠤᠯ', 'script' => 'Mong'],
        // 'mn_Mong_CN' => ['name' => 'Mongolian (Traditional Mongolian, China)', 'native' => 'ᠮᠤᠨᠭᠭᠤᠯ (ᠨᠡᠭᠦᠷ)', 'script' => 'Mong'],
        // 'mn_Mong_MN' => ['name' => 'Mongolian (Traditional Mongolian, Mongolia)', 'native' => 'ᠮᠤᠨᠭᠭᠤᠯ (ᠮᠣᠩᠭᠣᠯ)', 'script' => 'Mong'],
        // 'mfe' => ['name' => 'Morisyen', 'native' => 'Morisyen', 'script' => 'Latn'],
        // 'mfe_MU' => ['name' => 'Morisyen (Mauritius)', 'native' => 'Morisyen (Moris)', 'script' => 'Latn'],
        // 'mua' => ['name' => 'Mundang', 'native' => 'Mundang', 'script' => 'Latn'],
        // 'mua_CM' => ['name' => 'Mundang (Cameroon)', 'native' => 'Mundang (Kamɛrún)', 'script' => 'Latn'],
        // 'nqo' => ['name' => 'NʼKo', 'native' => 'ߒߞߏ', 'script' => 'Nkoo'],
        // 'nqo_GN' => ['name' => 'NʼKo (Guinea)', 'native' => 'ߒߞߏ (ߖߌ߬ߛߊ)', 'script' => 'Nkoo'],
        // 'naq' => ['name' => 'Nama', 'native' => 'Khoekhoegowab', 'script' => 'Latn'],
        // 'naq_NA' => ['name' => 'Nama (Namibia)', 'native' => 'Khoekhoegowab (Namibiab)', 'script' => 'Latn'],
        // 'ne' => ['name' => 'Nepali', 'native' => 'नेपाली', 'script' => 'Deva'],
        // 'ne_IN' => ['name' => 'Nepali (India)', 'native' => 'नेपाली (भारत)', 'script' => 'Deva'],
        // 'ne_NP' => ['name' => 'Nepali (Nepal)', 'native' => 'नेपाली (नेपाल)', 'script' => 'Deva'],
        // 'nnh' => ['name' => 'Ngiemboon', 'native' => 'Ngiemboon', 'script' => 'Latn'],
        // 'nnh_CM' => ['name' => 'Ngiemboon (Cameroon)', 'native' => 'Ngiemboon (Kàmɛrûn)', 'script' => 'Latn'],
        // 'jgo' => ['name' => 'Ngomba', 'native' => 'Ndaꞌa', 'script' => 'Latn'],
        // 'jgo_CM' => ['name' => 'Ngomba (Cameroon)', 'native' => 'Ndaꞌa (Kàmɛrûn)', 'script' => 'Latn'],
        // 'lrc_IQ' => ['name' => 'Northern Luri (Iraq)', 'native' => 'لۊری شومالی (Irāq)', 'script' => 'Latn'],
        // 'lrc_IR' => ['name' => 'Northern Luri (Iran)', 'native' => 'لۊری شومالی (Irān)', 'script' => 'Latn'],
        // 'nd' => ['name' => 'North Ndebele', 'native' => 'isiNdebele', 'script' => 'Latn'],
        // 'nd_ZW' => ['name' => 'North Ndebele (Zimbabwe)', 'native' => 'isiNdebele (Zimbabwe)', 'script' => 'Latn'],
        // 'no' => ['name' => 'Norwegian', 'native' => 'Norsk', 'script' => 'Latn'],
        // 'nb' => ['name' => 'Norwegian Bokmål', 'native' => 'Norsk bokmål', 'script' => 'Latn'],
        // 'nb_NO' => ['name' => 'Norwegian Bokmål (Norway)', 'native' => 'Norsk bokmål (Norge)', 'script' => 'Latn'],
        // 'nn' => ['name' => 'Norwegian Nynorsk', 'native' => 'Norsk nynorsk', 'script' => 'Latn'],
        // 'nn_NO' => ['name' => 'Norwegian Nynorsk (Norway)', 'native' => 'Norsk nynorsk (Noreg)', 'script' => 'Latn'],
        // 'nb_SJ' => ['name' => 'Norwegian Bokmål (Svalbard and Jan Mayen)', 'native' => 'Norsk bokmål (Svalbard og Jan Mayen)', 'script' => 'Latn'],
        // 'nus' => ['name' => 'Nuer', 'native' => 'Thok Nath', 'script' => 'Latn'],
        // 'nus_SD' => ['name' => 'Nuer (Sudan)', 'native' => 'Thok Nath (Sewdàn)', 'script' => 'Latn'],
        // 'nus_SS' => ['name' => 'Nuer (South Sudan)', 'native' => 'Thok Nath (SSD)', 'script' => 'Latn'],
        // 'nyn' => ['name' => 'Nyankole', 'native' => 'Runyankore', 'script' => 'Latn'],
        // 'nyn_UG' => ['name' => 'Nyankole (Uganda)', 'native' => 'Runyankore (Uganda)', 'script' => 'Latn'],
        // 'oc' => ['name' => 'Occitan', 'native' => 'Occitan', 'script' => 'Latn'],
        // 'oc_FR' => ['name' => 'Occitan (France)', 'native' => 'Occitan (França)', 'script' => 'Latn'],
        // 'or' => ['name' => 'Odia', 'native' => 'ଓଡ଼ିଆ', 'script' => 'Orya'],
        // 'or_IN' => ['name' => 'Odia (India)', 'native' => 'ଓଡ଼ିଆ (ଭାରତ)', 'script' => 'Orya'],
        // 'om' => ['name' => 'Oromo', 'native' => 'Afaan Oromoo', 'script' => 'Latn'],
        // 'om_ET' => ['name' => 'Oromo (Ethiopia)', 'native' => 'Afaan Oromoo (Itoophiyaa)', 'script' => 'Latn'],
        // 'om_KE' => ['name' => 'Oromo (Kenya)', 'native' => 'Afaan Oromoo (Keeniyaa)', 'script' => 'Latn'],
        // 'os' => ['name' => 'Ossetian', 'native' => 'Ирон', 'script' => 'Cyrl'],
        // 'os_GE' => ['name' => 'Ossetian (Georgia)', 'native' => 'Ирон (Гуырдзыстон)', 'script' => 'Cyrl'],
        // 'os_RU' => ['name' => 'Ossetian (Russia)', 'native' => 'Ирон (Росси)', 'script' => 'Cyrl'],
        // 'ps' => ['name' => 'Pashto', 'native' => 'پښتو', 'script' => 'Arab'],
        // 'ps_AF' => ['name' => 'Pashto (Afghanistan)', 'native' => 'پښتو (افغانستان)', 'script' => 'Arab'],
        // 'ps_PK' => ['name' => 'Pashto (Pakistan)', 'native' => 'پښتو (پاکستان)', 'script' => 'Arab'],
        // 'fa' => ['name' => 'Persian', 'native' => 'فارسی', 'script' => 'Arab'],
        // 'fa_AF' => ['name' => 'Persian (Afghanistan)', 'native' => 'فارسی (افغانستان)', 'script' => 'Arab'],
        // 'fa_IR' => ['name' => 'Persian (Iran)', 'native' => 'فارسی (ایران)', 'script' => 'Arab'],
        // 'pl' => ['name' => 'Polish', 'native' => 'Polski', 'script' => 'Latn'],
        // 'pl_PL' => ['name' => 'Polish (Poland)', 'native' => 'Polski (Polska)', 'script' => 'Latn'],
        // 'pt' => ['name' => 'Portuguese', 'native' => 'Português', 'script' => 'Latn'],
        // 'pt_AO' => ['name' => 'Portuguese (Angola)', 'native' => 'Português (Angola)', 'script' => 'Latn'],
        // 'pt_BR' => ['name' => 'Portuguese (Brazil)', 'native' => 'Português (Brasil)', 'script' => 'Latn'],
        // 'pt_CV' => ['name' => 'Portuguese (Cape Verde)', 'native' => 'Português (Cabo Verde)', 'script' => 'Latn'],
        // 'pt_GQ' => ['name' => 'Portuguese (Equatorial Guinea)', 'native' => 'Português (Guiné Equatorial)', 'script' => 'Latn'],
        // 'pt_GW' => ['name' => 'Portuguese (Guinea-Bissau)', 'native' => 'Português (Guiné-Bissau)', 'script' => 'Latn'],
        // 'pt_LU' => ['name' => 'Portuguese (Luxembourg)', 'native' => 'Português (Luxemburgo)', 'script' => 'Latn'],
        // 'pt_MO' => ['name' => 'Portuguese (Macau)', 'native' => 'Português (Macau)', 'script' => 'Latn'],
        // 'pt_MZ' => ['name' => 'Portuguese (Mozambique)', 'native' => 'Português (Moçambique)', 'script' => 'Latn'],
        // 'pt_PT' => ['name' => 'Portuguese (Portugal)', 'native' => 'Português (Portugal)', 'script' => 'Latn'],
        // 'pt_ST' => ['name' => 'Portuguese (São Tomé and Príncipe)', 'native' => 'Português (São Tomé e Príncipe)', 'script' => 'Latn'],
        // 'pt_CH' => ['name' => 'Portuguese (Switzerland)', 'native' => 'Português (Suíça)', 'script' => 'Latn'],
        // 'pt_TL' => ['name' => 'Portuguese (Timor-Leste)', 'native' => 'Português (Timor-Leste)', 'script' => 'Latn'],
        // 'prg_001' => ['name' => 'Prussian', 'native' => 'Prussian', 'script' => 'Latn'],
        // 'qps_ploca' => ['name' => 'Sign language', 'native' => 'Sign language', 'script' => 'Latn'],
        // 'qps_ploc' => ['name' => 'Sign language (Colombia)', 'native' => 'Sign language (Colombia)', 'script' => 'Latn'],
        // 'qps_plocm' => ['name' => 'Sign language (Mozambique)', 'native' => 'Sign language (Mozambique)', 'script' => 'Latn'],
        // 'pa' => ['name' => 'Punjabi', 'native' => 'ਪੰਜਾਬੀ', 'script' => 'Arab'],
        // 'pa_Arab' => ['name' => 'Punjabi (Arabic script)', 'native' => 'پنجابی (عربی حروف)', 'script' => 'Arab'],
        // 'pa_IN' => ['name' => 'Punjabi (India)', 'native' => 'ਪੰਜਾਬੀ (ਭਾਰਤ)', 'script' => 'Arab'],
        // 'pa_Arab_PK' => ['name' => 'Punjabi (Arabic, Pakistan)', 'native' => 'پنجابی (عربی, پاکستان)', 'script' => 'Arab'],
        // 'quz' => ['name' => 'Cusco Quechua', 'native' => 'Qusqu Qhichwa', 'script' => 'Latn'],
        // 'quz_BO' => ['name' => 'Cusco Quechua (Bolivia)', 'native' => 'Qusqu Qhichwa (Bolivia)', 'script' => 'Latn'],
        // 'quz_EC' => ['name' => 'Cusco Quechua (Ecuador)', 'native' => 'Qusqu Qhichwa (Ecuador)', 'script' => 'Latn'],
        // 'quz_PE' => ['name' => 'Cusco Quechua (Peru)', 'native' => 'Qusqu Qhichwa (Perú)', 'script' => 'Latn'],
        // 'ksh' => ['name' => 'Colognian', 'native' => 'Kölsch', 'script' => 'Latn'],
        // 'ksh_DE' => ['name' => 'Colognian (Germany)', 'native' => 'Kölsch (Deutschland)', 'script' => 'Latn'],
        // 'ro' => ['name' => 'Romanian', 'native' => 'română', 'script' => 'Latn'],
        // 'ro_MD' => ['name' => 'Romanian (Moldova)', 'native' => 'română (Republica Moldova)', 'script' => 'Latn'],
        // 'ro_RO' => ['name' => 'Romanian (Romania)', 'native' => 'română (România)', 'script' => 'Latn'],
        // 'rm' => ['name' => 'Romansh', 'native' => 'rumantsch', 'script' => 'Latn'],
        // 'rm_CH' => ['name' => 'Romansh (Switzerland)', 'native' => 'rumantsch (Svizra)', 'script' => 'Latn'],
        // 'rof' => ['name' => 'Rombo', 'native' => 'Kihorombo', 'script' => 'Latn'],
        // 'rof_TZ' => ['name' => 'Rombo (Tanzania)', 'native' => 'Kihorombo (Tanzania)', 'script' => 'Latn'],
        // 'rn' => ['name' => 'Rundi', 'native' => 'Ikirundi', 'script' => 'Latn'],
        // 'rn_BI' => ['name' => 'Rundi (Burundi)', 'native' => 'Ikirundi (Uburundi)', 'script' => 'Latn'],
        // 'ru' => ['name' => 'Russian', 'native' => 'русский', 'script' => 'Cyrl'],
        // 'ru_BY' => ['name' => 'Russian (Belarus)', 'native' => 'русский (Беларусь)', 'script' => 'Cyrl'],
        // 'ru_KZ' => ['name' => 'Russian (Kazakhstan)', 'native' => 'русский (Казахстан)', 'script' => 'Cyrl'],
        // 'ru_KG' => ['name' => 'Russian (Kyrgyzstan)', 'native' => 'русский (Киргизия)', 'script' => 'Cyrl'],
        // 'ru_MD' => ['name' => 'Russian (Moldova)', 'native' => 'русский (Молдова)', 'script' => 'Cyrl'],
        // 'ru_RU' => ['name' => 'Russian (Russia)', 'native' => 'русский (Россия)', 'script' => 'Cyrl'],
        // 'ru_UA' => ['name' => 'Russian (Ukraine)', 'native' => 'русский (Украина)', 'script' => 'Cyrl'],
        // 'rwk' => ['name' => 'Rwa', 'native' => 'Kiruwa', 'script' => 'Latn'],
        // 'rwk_TZ' => ['name' => 'Rwa (Tanzania)', 'native' => 'Kiruwa (Tanzania)', 'script' => 'Latn'],
        // 'ssy' => ['name' => 'Saho', 'native' => 'ሳሆ', 'script' => 'Latn'],
        // 'ssy_ER' => ['name' => 'Saho (Eritrea)', 'native' => 'ሳሆ (ኤርትራ)', 'script' => 'Latn'],
        // 'sah' => ['name' => 'Yakut', 'native' => 'саха тыла', 'script' => 'Cyrl'],
        // 'sah_RU' => ['name' => 'Yakut (Russia)', 'native' => 'саха тыла (Россия)', 'script' => 'Cyrl'],
        // 'saq' => ['name' => 'Samburu', 'native' => 'Kisampur', 'script' => 'Latn'],
        // 'saq_KE' => ['name' => 'Samburu (Kenya)', 'native' => 'Kisampur (Kenya)', 'script' => 'Latn'],
        // 'smn' => ['name' => 'Inari Sami', 'native' => 'sämikielâ', 'script' => 'Latn'],
        // 'smn_FI' => ['name' => 'Inari Sami (Finland)', 'native' => 'sämikielâ (Suomâ)', 'script' => 'Latn'],
        // 'smj' => ['name' => 'Lule Sami', 'native' => 'julev-sámegiella', 'script' => 'Latn'],
        // 'smj_NO' => ['name' => 'Lule Sami (Norway)', 'native' => 'julev-sámegiella (Norga)', 'script' => 'Latn'],
        // 'smj_SE' => ['name' => 'Lule Sami (Sweden)', 'native' => 'julev-sámegiella (Ruoŧŧa)', 'script' => 'Latn'],
        // 'se' => ['name' => 'Northern Sami', 'native' => 'davvisámegiella', 'script' => 'Latn'],
        // 'se_FI' => ['name' => 'Northern Sami (Finland)', 'native' => 'davvisámegiella (Suopma)', 'script' => 'Latn'],
        // 'se_NO' => ['name' => 'Northern Sami (Norway)', 'native' => 'davvisámegiella (Norga)', 'script' => 'Latn'],
        // 'se_SE' => ['name' => 'Northern Sami (Sweden)', 'native' => 'davvisámegiella (Ruoŧŧa)', 'script' => 'Latn'],
        // 'sms' => ['name' => 'Skolt Sami', 'native' => 'sääm´ǩiõll', 'script' => 'Latn'],
        // 'sms_FI' => ['name' => 'Skolt Sami (Finland)', 'native' => 'sääm´ǩiõll (Lää´ddjânnam)', 'script' => 'Latn'],
        // 'sma' => ['name' => 'Southern Sami', 'native' => 'Åarjelsaemiengïele', 'script' => 'Latn'],
        // 'sma_NO' => ['name' => 'Southern Sami (Norway)', 'native' => 'Åarjelsaemiengïele (Nöörje)', 'script' => 'Latn'],
        // 'sma_SE' => ['name' => 'Southern Sami (Sweden)', 'native' => 'Åarjelsaemiengïele (Sveerje)', 'script' => 'Latn'],
        // 'sg' => ['name' => 'Sango', 'native' => 'Sängö', 'script' => 'Latn'],
        // 'sg_CF' => ['name' => 'Sango (Central African Republic)', 'native' => 'Sängö (Ködörösêse tî Bêafrîka)', 'script' => 'Latn'],
        // 'sbp' => ['name' => 'Sangu', 'native' => 'Ishisangu', 'script' => 'Latn'],
        // 'sbp_TZ' => ['name' => 'Sangu (Tanzania)', 'native' => 'Ishisangu (Tanzania)', 'script' => 'Latn'],
        // 'sa' => ['name' => 'Sanskrit', 'native' => 'संस्कृतम्', 'script' => 'Deva'],
        // 'sa_IN' => ['name' => 'Sanskrit (India)', 'native' => 'संस्कृतम् (भारतम्)', 'script' => 'Deva'],
        // 'gd' => ['name' => 'Scottish Gaelic', 'native' => 'Gàidhlig', 'script' => 'Latn'],
        // 'gd_GB' => ['name' => 'Scottish Gaelic (United Kingdom)', 'native' => 'Gàidhlig (An Rìoghachd Aonaichte)', 'script' => 'Latn'],
        // 'seh' => ['name' => 'Sena', 'native' => 'sena', 'script' => 'Latn'],
        // 'seh_MZ' => ['name' => 'Sena (Mozambique)', 'native' => 'sena (Moçambique)', 'script' => 'Latn'],
        // 'sr_Cyrl' => ['name' => 'Serbian (Cyrillic)', 'native' => 'српски', 'script' => 'Cyrl'],
        // 'sr_Cyrl_BA' => ['name' => 'Serbian (Cyrillic, Bosnia and Herzegovina)', 'native' => 'српски (Босна и Херцеговина)', 'script' => 'Cyrl'],
        // 'sr_Cyrl_ME' => ['name' => 'Serbian (Cyrillic, Montenegro)', 'native' => 'српски (Црна Гора)', 'script' => 'Cyrl'],
        // 'sr_Cyrl_RS' => ['name' => 'Serbian (Cyrillic, Serbia)', 'native' => 'српски (Србија)', 'script' => 'Cyrl'],
        // 'sr_Cyrl_CS' => ['name' => 'Serbian (Cyrillic, Serbia and Montenegro)', 'native' => 'српски (Србија и Црна Гора)', 'script' => 'Cyrl'],
        // 'sr_Latn' => ['name' => 'Serbian (Latin)', 'native' => 'srpski', 'script' => 'Latn'],
        // 'sr' => ['name' => 'Serbian', 'native' => 'српски', 'script' => 'Cyrl'],
        // 'sr_Latn_BA' => ['name' => 'Serbian (Latin, Bosnia and Herzegovina)', 'native' => 'srpski (Bosna i Hercegovina)', 'script' => 'Latn'],
        // 'sr_Latn_ME' => ['name' => 'Serbian (Latin, Montenegro)', 'native' => 'srpski (Crna Gora)', 'script' => 'Latn'],
        // 'sr_Latn_RS' => ['name' => 'Serbian (Latin, Serbia)', 'native' => 'srpski (Srbija)', 'script' => 'Latn'],
        // 'sr_Latn_CS' => ['name' => 'Serbian (Latin, Serbia and Montenegro)', 'native' => 'srpski (Srbija i Crna Gora)', 'script' => 'Latn'],
        // 'nso' => ['name' => 'Northern Sotho', 'native' => 'Sesotho sa Leboa', 'script' => 'Latn'],
        // 'nso_ZA' => ['name' => 'Northern Sotho (South Africa)', 'native' => 'Sesotho sa Leboa (Afrika Borwa)', 'script' => 'Latn'],
        // 'tn' => ['name' => 'Tswana', 'native' => 'Setswana', 'script' => 'Latn'],
        // 'tn_BW' => ['name' => 'Tswana (Botswana)', 'native' => 'Setswana (Botswana)', 'script' => 'Latn'],
        // 'tn_ZA' => ['name' => 'Tswana (South Africa)', 'native' => 'Setswana (Afrika Borwa)', 'script' => 'Latn'],
        // 'ksb' => ['name' => 'Shambala', 'native' => 'Kishambaa', 'script' => 'Latn'],
        // 'ksb_TZ' => ['name' => 'Shambala (Tanzania)', 'native' => 'Kishambaa (Tanzania)', 'script' => 'Latn'],
        // 'sn' => ['name' => 'Shona', 'native' => 'chiShona', 'script' => 'Latn'],
        // 'sn_Latn' => ['name' => 'Shona (Latin)', 'native' => 'chiShona', 'script' => 'Latn'],
        // 'sn_Latn_ZW' => ['name' => 'Shona (Latin, Zimbabwe)', 'native' => 'chiShona (Zimbabwe)', 'script' => 'Latn'],
        // 'sd' => ['name' => 'Sindhi', 'native' => 'سنڌي', 'script' => 'Arab'],
        // 'sd_Arab' => ['name' => 'Sindhi (Arabic)', 'native' => 'سنڌي (عربي)', 'script' => 'Arab'],
        // 'sd_Arab_PK' => ['name' => 'Sindhi (Arabic, Pakistan)', 'native' => 'سنڌي (عربي, پاڪستان)', 'script' => 'Arab'],
        // 'si' => ['name' => 'Sinhala', 'native' => 'සිංහල', 'script' => 'Sinh'],
        // 'si_LK' => ['name' => 'Sinhala (Sri Lanka)', 'native' => 'සිංහල (ශ්‍රී ලංකාව)', 'script' => 'Sinh'],
        // 'sk' => ['name' => 'Slovak', 'native' => 'slovenčina', 'script' => 'Latn'],
        // 'sk_SK' => ['name' => 'Slovak (Slovakia)', 'native' => 'slovenčina (Slovensko)', 'script' => 'Latn'],
        // 'sl' => ['name' => 'Slovenian', 'native' => 'slovenščina', 'script' => 'Latn'],
        // 'sl_SI' => ['name' => 'Slovenian (Slovenia)', 'native' => 'slovenščina (Slovenija)', 'script' => 'Latn'],
        // 'xog' => ['name' => 'Soga', 'native' => 'Olusoga', 'script' => 'Latn'],
        // 'xog_UG' => ['name' => 'Soga (Uganda)', 'native' => 'Olusoga (Yuganda)', 'script' => 'Latn'],
        // 'so' => ['name' => 'Somali', 'native' => 'Soomaaliga', 'script' => 'Latn'],
        // 'so_DJ' => ['name' => 'Somali (Djibouti)', 'native' => 'Soomaaliga (Jabuuti)', 'script' => 'Latn'],
        // 'so_ET' => ['name' => 'Somali (Ethiopia)', 'native' => 'Soomaaliga (Itoobiya)', 'script' => 'Latn'],
        // 'so_KE' => ['name' => 'Somali (Kenya)', 'native' => 'Soomaaliga (Kenya)', 'script' => 'Latn'],
        // 'so_SO' => ['name' => 'Somali (Somalia)', 'native' => 'Soomaaliga (Soomaaliya)', 'script' => 'Latn'],
        // 'st' => ['name' => 'Southern Sotho', 'native' => 'Sesotho', 'script' => 'Latn'],
        // 'st_ZA' => ['name' => 'Southern Sotho (South Africa)', 'native' => 'Sesotho (Afrika Borwa)', 'script' => 'Latn'],
        // 'nr' => ['name' => 'Ndebele', 'native' => 'isiNdebele', 'script' => 'Latn'],
        // 'nr_ZA' => ['name' => 'Ndebele (South Africa)', 'native' => 'isiNdebele (iSewula Afrika)', 'script' => 'Latn'],
        // 'st_LS' => ['name' => 'Southern Sotho (Lesotho)', 'native' => 'Sesotho (Lesotho)', 'script' => 'Latn'],
        // 'es' => ['name' => 'Spanish', 'native' => 'español', 'script' => 'Latn'],
        // 'es_AR' => ['name' => 'Spanish (Argentina)', 'native' => 'español (Argentina)', 'script' => 'Latn'],
        // 'es_BZ' => ['name' => 'Spanish (Belize)', 'native' => 'español (Belice)', 'script' => 'Latn'],
        // 'es_VE' => ['name' => 'Spanish (Venezuela)', 'native' => 'español (Venezuela)', 'script' => 'Latn'],
        // 'es_BO' => ['name' => 'Spanish (Bolivia)', 'native' => 'español (Bolivia)', 'script' => 'Latn'],
        // 'es_BR' => ['name' => 'Spanish (Brazil)', 'native' => 'español (Brasil)', 'script' => 'Latn'],
        // 'es_CL' => ['name' => 'Spanish (Chile)', 'native' => 'español (Chile)', 'script' => 'Latn'],
        // 'es_CO' => ['name' => 'Spanish (Colombia)', 'native' => 'español (Colombia)', 'script' => 'Latn'],
        // 'es_CR' => ['name' => 'Spanish (Costa Rica)', 'native' => 'español (Costa Rica)', 'script' => 'Latn'],
        // 'es_CU' => ['name' => 'Spanish (Cuba)', 'native' => 'español (Cuba)', 'script' => 'Latn'],
        // 'es_DO' => ['name' => 'Spanish (Dominican Republic)', 'native' => 'español (República Dominicana)', 'script' => 'Latn'],
        // 'es_EC' => ['name' => 'Spanish (Ecuador)', 'native' => 'español (Ecuador)', 'script' => 'Latn'],
        // 'es_SV' => ['name' => 'Spanish (El Salvador)', 'native' => 'español (El Salvador)', 'script' => 'Latn'],
        // 'es_GQ' => ['name' => 'Spanish (Equatorial Guinea)', 'native' => 'español (Guinea Ecuatorial)', 'script' => 'Latn'],
        // 'es_GT' => ['name' => 'Spanish (Guatemala)', 'native' => 'español (Guatemala)', 'script' => 'Latn'],
        // 'es_HN' => ['name' => 'Spanish (Honduras)', 'native' => 'español (Honduras)', 'script' => 'Latn'],
        // 'es_419' => ['name' => 'Spanish (Latin America)', 'native' => 'español (Latinoamérica)', 'script' => 'Latn'],
        // 'es_MX' => ['name' => 'Spanish (Mexico)', 'native' => 'español (México)', 'script' => 'Latn'],
        // 'es_NI' => ['name' => 'Spanish (Nicaragua)', 'native' => 'español (Nicaragua)', 'script' => 'Latn'],
        // 'es_PA' => ['name' => 'Spanish (Panama)', 'native' => 'español (Panamá)', 'script' => 'Latn'],
        // 'es_PY' => ['name' => 'Spanish (Paraguay)', 'native' => 'español (Paraguay)', 'script' => 'Latn'],
        // 'es_PE' => ['name' => 'Spanish (Peru)', 'native' => 'español (Perú)', 'script' => 'Latn'],
        // 'es_PH' => ['name' => 'Spanish (Philippines)', 'native' => 'español (Filipinas)', 'script' => 'Latn'],
        // 'es_PR' => ['name' => 'Spanish (Puerto Rico)', 'native' => 'español (Puerto Rico)', 'script' => 'Latn'],
        // 'es_ES_tradnl' => ['name' => 'Spanish (Spain, Traditional Sort)', 'native' => 'español (España, tradicional)', 'script' => 'Latn'],
        // 'es_ES' => ['name' => 'Spanish (Spain)', 'native' => 'español (España)', 'script' => 'Latn'],
        // 'es_US' => ['name' => 'Spanish (United States)', 'native' => 'español (Estados Unidos)', 'script' => 'Latn'],
        // 'es_UY' => ['name' => 'Spanish (Uruguay)', 'native' => 'español (Uruguay)', 'script' => 'Latn'],
        // 'zgh' => ['name' => 'Standard Moroccan Tamazight', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'script' => 'Latn'],
        // 'zgh_Tfng_MA' => ['name' => 'Standard Moroccan Tamazight (Tifinagh, Morocco)', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵜⵉⴼⵉⵏⴰⵖ, ⵍⵎⴰⵖⵔⵉⴱ)', 'script' => 'Tfng'],
        // 'zgh_Tfng' => ['name' => 'Standard Moroccan Tamazight (Tifinagh)', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵜⵉⴼⵉⵏⴰⵖ)', 'script' => 'Tfng'],
        // 'ss' => ['name' => 'Swati', 'native' => 'siSwati', 'script' => 'Latn'],
        // 'ss_ZA' => ['name' => 'Swati (South Africa)', 'native' => 'siSwati (South Africa)', 'script' => 'Latn'],
        // 'ss_SZ' => ['name' => 'Swati (Eswatini)', 'native' => 'siSwati (Eswatini)', 'script' => 'Latn'],
        // 'sv' => ['name' => 'Swedish', 'native' => 'svenska', 'script' => 'Latn'],
        // 'sv_AX' => ['name' => 'Swedish (Åland Islands)', 'native' => 'svenska (Åland)', 'script' => 'Latn'],
        // 'sv_FI' => ['name' => 'Swedish (Finland)', 'native' => 'svenska (Finland)', 'script' => 'Latn'],
        // 'sv_SE' => ['name' => 'Swedish (Sweden)', 'native' => 'svenska (Sverige)', 'script' => 'Latn'],
        // 'syr' => ['name' => 'Syriac', 'native' => 'ܣܘܪܝܝܐ', 'script' => 'Syrc'],
        // 'syr_SY' => ['name' => 'Syriac (Syria)', 'native' => 'ܣܘܪܝܝܐ (ܣܘܪܝܐ)', 'script' => 'Syrc'],
        // 'shi' => ['name' => 'Tachelhit', 'native' => 'ⵜⴰⵛⵍⵃⵉⵜ', 'script' => 'Tfng'],
        // 'shi_Tfng' => ['name' => 'Tachelhit (Tifinagh)', 'native' => 'ⵜⴰⵛⵍⵃⵉⵜ (ⵜⵉⴼⵉⵏⴰⵖ)', 'script' => 'Tfng'],
        // 'shi_Tfng_MA' => ['name' => 'Tachelhit (Tifinagh, Morocco)', 'native' => 'ⵜⴰⵛⵍⵃⵉⵜ (ⵜⵉⴼⵉⵏⴰⵖ, ⵍⵎⴰⵖⵔⵉⴱ)', 'script' => 'Tfng'],
        // 'shi_Latn' => ['name' => 'Tachelhit (Latin)', 'native' => 'Tachelhit (Latin)', 'script' => 'Latn'],
        // 'shi_Latn_MA' => ['name' => 'Tachelhit (Latin, Morocco)', 'native' => 'Tachelhit (Latin, Morocco)', 'script' => 'Latn'],
        // 'dav' => ['name' => 'Taita', 'native' => 'Kɨdavida', 'script' => 'Latn'],
        // 'dav_KE' => ['name' => 'Taita (Kenya)', 'native' => 'Kɨdavida (Kenya)', 'script' => 'Latn'],
        // 'tg' => ['name' => 'Tajik', 'native' => 'тоҷикӣ', 'script' => 'Cyrl'],
        // 'tg_Cyrl' => ['name' => 'Tajik (Cyrillic)', 'native' => 'тоҷикӣ (кирилл)', 'script' => 'Cyrl'],
        // 'tg_Cyrl_TJ' => ['name' => 'Tajik (Cyrillic, Tajikistan)', 'native' => 'тоҷикӣ (кирилл, Тоҷикистон)', 'script' => 'Cyrl'],
        // 'tzm' => ['name' => 'Tamazight (Central Atlas)', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵜⴰⵙⵓⵙⴰⵜ ⵏ ⵜⴰⵏⴰⵎⵎⴰⵜ)', 'script' => 'Latn'],
        // 'tzm_Latn' => ['name' => 'Tamazight (Latin)', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⴰⵜⵉⵏ)', 'script' => 'Latn'],
        // 'tzm_Latn_DZ' => ['name' => 'Tamazight (Latin, Algeria)', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⴰⵜⵉⵏ, ⴷⵣⴰⵢⴻⵔ)', 'script' => 'Latn'],
        // 'ta' => ['name' => 'Tamil', 'native' => 'தமிழ்', 'script' => 'Taml'],
        // 'ta_IN' => ['name' => 'Tamil (India)', 'native' => 'தமிழ் (இந்தியா)', 'script' => 'Taml'],
        // 'ta_MY' => ['name' => 'Tamil (Malaysia)', 'native' => 'தமிழ் (மலேஷியா)', 'script' => 'Taml'],
        // 'ta_SG' => ['name' => 'Tamil (Singapore)', 'native' => 'தமிழ் (சிங்கப்பூர்)', 'script' => 'Taml'],
        // 'ta_LK' => ['name' => 'Tamil (Sri Lanka)', 'native' => 'தமிழ் (இலங்கை)', 'script' => 'Taml'],
        // 'twq' => ['name' => 'Tasawaq', 'native' => 'Tasawaq', 'script' => 'Latn'],
        // 'twq_NE' => ['name' => 'Tasawaq (Niger)', 'native' => 'Tasawaq (Niger)', 'script' => 'Latn'],
        // 'tt' => ['name' => 'Tatar', 'native' => 'татарча', 'script' => 'Cyrl'],
        // 'tt_RU' => ['name' => 'Tatar (Russia)', 'native' => 'татарча (Россия)', 'script' => 'Cyrl'],
        // 'te' => ['name' => 'Telugu', 'native' => 'తెలుగు', 'script' => 'Telu'],
        // 'te_IN' => ['name' => 'Telugu (India)', 'native' => 'తెలుగు (భారతదేశం)', 'script' => 'Telu'],
        // 'teo' => ['name' => 'Teso', 'native' => 'Kiteso', 'script' => 'Latn'],
        // 'teo_KE' => ['name' => 'Teso (Kenya)', 'native' => 'Kiteso (Kenya)', 'script' => 'Latn'],
        // 'teo_UG' => ['name' => 'Teso (Uganda)', 'native' => 'Kiteso (Uganda)', 'script' => 'Latn'],
        // 'th' => ['name' => 'Thai', 'native' => 'ไทย', 'script' => 'Thai'],
        // 'th_TH' => ['name' => 'Thai (Thailand)', 'native' => 'ไทย (ประเทศไทย)', 'script' => 'Thai'],
        // 'bo' => ['name' => 'Tibetan', 'native' => 'བོད་སྐད་', 'script' => 'Tibt'],
        // 'bo_IN' => ['name' => 'Tibetan (India)', 'native' => 'བོད་སྐད་ (རྒྱ་གར)', 'script' => 'Tibt'],
        // 'bo_CN' => ['name' => 'Tibetan (China)', 'native' => 'བོད་སྐད་ (ཀྲུང་ཧྭ)', 'script' => 'Tibt'],
        // 'tig' => ['name' => 'Tigre', 'native' => 'ትግረ', 'script' => 'Ethi'],
        // 'tig_ER' => ['name' => 'Tigre (Eritrea)', 'native' => 'ትግረ (ኤርትራ)', 'script' => 'Ethi'],
        // 'ti' => ['name' => 'Tigrinya', 'native' => 'ትግርኛ', 'script' => 'Ethi'],
        // 'ti_ER' => ['name' => 'Tigrinya (Eritrea)', 'native' => 'ትግርኛ (ኤርትራ)', 'script' => 'Ethi'],
        // 'ti_ET' => ['name' => 'Tigrinya (Ethiopia)', 'native' => 'ትግርኛ (ኢትዮጵያ)', 'script' => 'Ethi'],
        // 'to' => ['name' => 'Tongan', 'native' => 'lea fakatonga', 'script' => 'Latn'],
        // 'to_TO' => ['name' => 'Tongan (Tonga)', 'native' => 'lea fakatonga (Tonga)', 'script' => 'Latn'],
        // 'ts' => ['name' => 'Tsonga', 'native' => 'Xitsonga', 'script' => 'Latn'],
        // 'ts_ZA' => ['name' => 'Tsonga (South Africa)', 'native' => 'Xitsonga (Afurika Tshipembe)', 'script' => 'Latn'],
        // 'tr' => ['name' => 'Turkish', 'native' => 'Türkçe', 'script' => 'Latn'],
        // 'tr_CY' => ['name' => 'Turkish (Cyprus)', 'native' => 'Türkçe (Kıbrıs)', 'script' => 'Latn'],
        // 'tr_TR' => ['name' => 'Turkish (Turkey)', 'native' => 'Türkçe (Türkiye)', 'script' => 'Latn'],
        // 'tk' => ['name' => 'Turkmen', 'native' => 'Türkmençe', 'script' => 'Latn'],
        // 'tk_TM' => ['name' => 'Turkmen (Turkmenistan)', 'native' => 'Türkmençe (Türkmenistan)', 'script' => 'Latn'],
        // 'uk' => ['name' => 'Ukrainian', 'native' => 'українська', 'script' => 'Cyrl'],
        // 'uk_UA' => ['name' => 'Ukrainian (Ukraine)', 'native' => 'українська (Україна)', 'script' => 'Cyrl'],
        // 'hsb' => ['name' => 'Upper Sorbian', 'native' => 'hornjoserbšćina', 'script' => 'Latn'],
        // 'hsb_DE' => ['name' => 'Upper Sorbian (Germany)', 'native' => 'hornjoserbšćina (Němska)', 'script' => 'Latn'],
        // 'ur' => ['name' => 'Urdu', 'native' => 'اُردو', 'script' => 'Arab'],
        // 'ur_IN' => ['name' => 'Urdu (India)', 'native' => 'اُردو (بھارت)', 'script' => 'Arab'],
        // 'ur_PK' => ['name' => 'Urdu (Pakistan)', 'native' => 'اُردو (پاکستان)', 'script' => 'Arab'],
        // 'ug' => ['name' => 'Uyghur', 'native' => 'ئۇيغۇرچە', 'script' => 'Arab'],
        // 'ug_CN' => ['name' => 'Uyghur (China)', 'native' => 'ئۇيغۇرچە (جۇڭخۇا)', 'script' => 'Arab'],
        // 'uz_Arab' => ['name' => 'Uzbek (Arabic)', 'native' => 'اۉزبېک (عرب)', 'script' => 'Arab'],
        // 'uz_Arab_AF' => ['name' => 'Uzbek (Arabic, Afghanistan)', 'native' => 'اۉزبېک (عرب, افغانستان)', 'script' => 'Arab'],
        // 'uz_Cyrl' => ['name' => 'Uzbek (Cyrillic)', 'native' => 'ўзбекча (Кирил)', 'script' => 'Cyrl'],
        // 'uz_Cyrl_UZ' => ['name' => 'Uzbek (Cyrillic, Uzbekistan)', 'native' => 'ўзбекча (Кирил, Ўзбекистон)', 'script' => 'Cyrl'],
        // 'uz' => ['name' => 'Uzbek (Latin)', 'native' => 'o‘zbekcha', 'script' => 'Latn'],
        // 'uz_Latn' => ['name' => 'Uzbek (Latin)', 'native' => 'o‘zbekcha', 'script' => 'Latn'],
        // 'uz_Latn_UZ' => ['name' => 'Uzbek (Latin, Uzbekistan)', 'native' => 'o‘zbekcha (Lotin, O‘zbekiston)', 'script' => 'Latn'],
        // 'vai' => ['name' => 'Vai', 'native' => 'ꕙꔤ', 'script' => 'Vaii'],
        // 'vai_Vaii' => ['name' => 'Vai (Vai)', 'native' => 'ꕙꔤ (Vai)', 'script' => 'Vaii'],
        // 'vai_Vaii_LR' => ['name' => 'Vai (Vai, Liberia)', 'native' => 'ꕙꔤ (Vai, Liberia)', 'script' => 'Vaii'],
        // 'vai_Latn_LR' => ['name' => 'Vai (Latin, Liberia)', 'native' => 'Vai (Latin, Liberia)', 'script' => 'Latn'],
        // 'vai_Latn' => ['name' => 'Vai (Latin)', 'native' => 'Vai (Latin)', 'script' => 'Latn'],
        // 'ca_ES_valencia' => ['name' => 'Valencian', 'native' => 'Valencià', 'script' => 'Latn'],
        // 've' => ['name' => 'Venda', 'native' => 'Tshivenḓa', 'script' => 'Latn'],
        // 've_ZA' => ['name' => 'Venda (South Africa)', 'native' => 'Tshivenḓa (Afurika Tshipembe)', 'script' => 'Latn'],
        // 'vi' => ['name' => 'Vietnamese', 'native' => 'Tiếng Việt', 'script' => 'Latn'],
        // 'vi_VN' => ['name' => 'Vietnamese (Vietnam)', 'native' => 'Tiếng Việt (Việt Nam)', 'script' => 'Latn'],
        // 'vo' => ['name' => 'Volapük', 'native' => 'Volapük', 'script' => 'Latn'],
        // 'vo_001' => ['name' => 'Volapük (World)', 'native' => 'Volapük (World)', 'script' => 'Latn'],
        // 'vun' => ['name' => 'Vunjo', 'native' => 'Kyivunjo', 'script' => 'Latn'],
        // 'vun_TZ' => ['name' => 'Vunjo (Tanzania)', 'native' => 'Kyivunjo (Tanzania)', 'script' => 'Latn'],
        // 'wae' => ['name' => 'Walser', 'native' => 'Walser', 'script' => 'Latn'],
        // 'wae_CH' => ['name' => 'Walser (Switzerland)', 'native' => 'Walser (Schweiz)', 'script' => 'Latn'],
        // 'cy' => ['name' => 'Welsh', 'native' => 'Cymraeg', 'script' => 'Latn'],
        // 'cy_GB' => ['name' => 'Welsh (United Kingdom)', 'native' => 'Cymraeg (Y Deyrnas Unedig)', 'script' => 'Latn'],
        // 'wal' => ['name' => 'Wolaytta', 'native' => 'ወላይታቱ', 'script' => 'Ethi'],
        // 'wal_ET' => ['name' => 'Wolaytta (Ethiopia)', 'native' => 'ወላይታቱ (ኢትዮጵያ)', 'script' => 'Ethi'],
        // 'wo' => ['name' => 'Wolof', 'native' => 'Wolof', 'script' => 'Latn'],
        // 'wo_SN' => ['name' => 'Wolof (Senegal)', 'native' => 'Wolof (Senegaal)', 'script' => 'Latn'],
        // 'xh' => ['name' => 'Xhosa', 'native' => 'isiXhosa', 'script' => 'Latn'],
        // 'xh_ZA' => ['name' => 'Xhosa (South Africa)', 'native' => 'isiXhosa (iNingizimu Afrika)', 'script' => 'Latn'],
        // 'yav' => ['name' => 'Yangben', 'native' => 'nuasueŋa', 'script' => 'Latn'],
        // 'yav_CM' => ['name' => 'Yangben (Cameroon)', 'native' => 'nuasueŋa (kameruŋ)', 'script' => 'Latn'],
        // 'ii' => ['name' => 'Yi', 'native' => 'ꆇꉙ', 'script' => 'Yiii'],
        // 'ii_CN' => ['name' => 'Yi (China)', 'native' => 'ꆇꉙ (中国)', 'script' => 'Yiii'],
        // 'yi_001' => ['name' => 'Yiddish (World)', 'native' => 'ייִדיש (וועלט)', 'script' => 'Latn'],
        // 'yo' => ['name' => 'Yoruba', 'native' => 'Èdè Yorùbá', 'script' => 'Latn'],
        // 'yo_BJ' => ['name' => 'Yoruba (Benin)', 'native' => 'Èdè Yorùbá (Orílẹ́ède Bẹ̀nẹ̀)', 'script' => 'Latn'],
        // 'yo_NG' => ['name' => 'Yoruba (Nigeria)', 'native' => 'Èdè Yorùbá (Nàìjíríà)', 'script' => 'Latn'],
        // 'dje' => ['name' => 'Zarma', 'native' => 'Zarmaciine', 'script' => 'Latn'],
        // 'dje_NE' => ['name' => 'Zarma (Niger)', 'native' => 'Zarmaciine (Nižɛri)', 'script' => 'Latn'],
        // 'zu' => ['name' => 'Zulu', 'native' => 'isiZulu', 'script' => 'Latn'],
        // 'zu_ZA' => ['name' => 'Zulu (South Africa)', 'native' => 'isiZulu (iNingizimu Afrika)', 'script' => 'Latn'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Default Locale
    |--------------------------------------------------------------------------
    |
    | The default locale used by Turjuman when no locale is detected.
    | Change the value to the desired default locale code.
    | 
    */

    'default_locale' => 'ar',

    /*
    |--------------------------------------------------------------------------
    | Locale Display Location
    |--------------------------------------------------------------------------
    |
    | Defines where Turjuman will display the locale in the URL.
    | 
    | Options:
    | 1. positive-integer => Display as a URL segment (e.g., 'https://www.example.com/ar').
    | 2. string => Display as a query parameter (e.g., 'https://www.example.com?lang=ar').
    | 3. null => Set the locale internally but hide it from the URL (prioritizes over 'hide_default').
    |
    */

    'display_location' => 1,

    /*
    |--------------------------------------------------------------------------
    | Hide Default Locale From URL
    |--------------------------------------------------------------------------
    |
    | Controls whether to hide the default locale from the URL.
    | If set to true, visiting 'https://www.example.com/ar/about' will redirect to 'https://www.example.com/about'.
    |
    */

    'hide_default' => true,

    /*
    |--------------------------------------------------------------------------
    | Route Aliases
    |--------------------------------------------------------------------------
    |
    | Define route aliases for translated routes when 'display_location' is segment or hidden.
    | Example: 'https://www.example.com/ar/عنا' instead of 'https://www.example.com/ar/about'.
    |
    */

    'route_aliases' => [
        /*'ar' => [
            '/about' => '/عنا'
        ]*/
    ],

    /*
    |--------------------------------------------------------------------------
    | Locale Identifier
    |--------------------------------------------------------------------------
    |
    | The locale identifier used in url parameters, session, cookies, and form input to identify the current locale.
    |
    */

    'locale_identifier' => '_locale',
];